### ISSUE TITLE
RFC-2: Condition maxFulfillmentLength OER encoding

### ISSUE THREAD

**Issue by nbougalis** [interledger/rfcs#105]
The existing proposal defines the binary encoding of a condition as follows:

```
Condition ::= SEQUENCE {
    type ConditionType,
    featureBitmask OCTET STRING,
    fingerprint OCTET STRING,
    maxFulfillmentLength INTEGER (0..MAX)
}
```

I propose imposing a maximum length on the  `maxFulfillmentLength` field and placing it before the `fingerprint` object, so that the condition looks like this:

```
Condition ::= SEQUENCE {
type ConditionType,
featureBitmask OCTET STRING,
maxFulfillmentLength INTEGER (0..4294967295)
fingerprint OCTET STRING,
}
```

Limiting the largest fulfillment allowable under the specification to 4GB is more than reasonable. If we prefer to limit to 2GB so that 32-bit signed values fit, that's also possible; we simply adjust the limit to `2147483647`. Even 2GB is a _ridiculously_ large fulfillment.

This will _slightly_ increase the length of a fulfillment since the length will always be 4 bytes long.

Tangentially related: this moves us towards a direction where a condition always has a fixed-size encoding. This could be a benefit.

**Comment by adrianhopebailie** [comment]
As an aside, it feels like such a large fulfillment is dangerous anyway. A validation service that is consuming gigabytes of data unchecked for a single fulfillment seems like a soft target.

Can we pick more "sane" numbers and protect ourselves by versioning the conditions? (I can't recall why we dropped the version)

That may also allow us to stick with a fixed size for the fingerprint and bitmask as discussed in #106

**Comment by justmoon** [comment]
This was adopted in draft-02.
