### ISSUE TITLE
RFC-2: Fixed-size OER encoding of Condition

### ISSUE THREAD

**Issue by nbougalis** [interledger/rfcs#106]
Continuing from #105, having a `Condition` have a fixed-size binary encoding is a good idea. Assuming #105 is adopted, the `fingerprint` and `featureBitmask` fields use variable-length encoding.

We should consider imposing a limit on the number of "features" available. For example, we could allow up to 32 features.

Currently, we have five features: sha256, preimage, prefix, threshold, rsa_pss and ed25519. With a 4 byte unsigned int, we still have space for `(32-5) = 27` additional features. Alternatively, we could just make the field 64 bits, allowing us `(64-5) = 59` additional features. We can gain one extra bit by removing the `sha256` feature and defining that algorithm as always implicitly available.

Second, we should consider making the `fingerprint` field a fixed sized, instead of a variable-length octet string. The specification already includes SHA256, which, conveniently, outputs 32 bytes which is the current size of a fulfillment. So we could just define conditions to be exactly 32 bytes.

Potential problems with that is that SHA256 has shown some weaknesses. Our construct is fine for now, but we should be conservative. We could go for SHA512, doubling the number of bits available.

Doing so means that our hashlocks won't be directly compatible with Bitcoin's `OP_HASH256` and will increase the size of a condition, which are both things to consider; on the plus side any implementation which has SHA256 available should, also have SHA512 since they're in the same SHA-2 family.

**Comment by adrianhopebailie** [comment]
As mentioned in #105 wouldn't adding a version allow us to be more rigid. i.e. Fix the bit-mask to 1 byte and the fingerprint to 32.

The cost is a single byte at the beginning that defaults to 0x00 and gives us 255 future versions.

**Comment by justmoon** [comment]
In collaboration with @nbougalis and @adrianhopebailie, we ended up using BIT STRING encoding which is variable length. However, simple conditions (those that can't have subconditions) no longer contain a subtypes field at all and are therefore constant size.
