### ISSUE TITLE
RFC-2: RSA-PSS & ED25519 conditions given same key

### ISSUE THREAD

**Issue by nbougalis** [interledger/rfcs#109]
In Section 4.5.1,  we define the the condition associated with an Ed25519 cryptocondition as follows:

>    The fingerprint of a ED25519 condition is the 32 byte Ed25519 public key.  Since the public key is already very small, we do not hash it.

This means that all fulfillments which share the same Ed25519 private key K will generate identical conditions (upto the fulfillment length).

Consider this example: both fulfillments share the same secret key; one is for the string `"abc"` and the other for the string `"def"` (not that it matters, but these are C-style strings, so the buffer is 4 bytes because of the trailing null):

```
f1 (m='abc'):
fulfillment: cf:4:RCm [...] F7PIO
  condition: cc:4:20:RCmTBlAEqh5MSPTdAVgZTAI0m8xmTNluQA6iaZGKjVE:96
f2 (m='def'):
fulfillment: cf:4:RCm [...] ZdcwN
  condition: cc:4:20:RCmTBlAEqh5MSPTdAVgZTAI0m8xmTNluQA6iaZGKjVE:96
Comparing f1 and f2's conditions:identical
```

This is an issue, since distinct fulfillments generate a single condition. which means the condition can't be used as a key, even if the entire condition is used as recommended by 2.4.3.

Additionally, depending on how ed25519 fulfillments are used, this can surprise people. Consider the case where someone generates multiple ed25519 fulfillments, all from his well-known key. Depending on how a fulfillment is validated (that is, given a fulfillment `f` and a condition `c`, is `f.condition() == c` sufficient to satisfy?) this can mean that as soon as a single fulfillment is revealed, it can be copied and used to satisfy any outstanding condition.

I guess guidance that ed25519 conditions should always be wrapped inside a prefix that is unique sorta, kinda addresses this. But it ends up effectively creating second-class cryptoconditions that can't be safely used in intuitive ways.

The same applies to RSA-SHA-256: the condition has only the modulus, which could be shared across multiple fulfillments if someone is using a single RSA key.

I believe this needs to be fixed, and suggest we do so by making the fingerprint of those condition be equal to the SHA256 hash of the fulfillment payload. For ED25519, this is defined in 4.5.2 as:

```
   Ed25519FulfillmentPayload ::= SEQUENCE {
     publicKey OCTET STRING (SIZE(32)),
     signature OCTET STRING (SIZE(64))
   }
```
For RSA-SHA-256 it's defined in 4.4.2 as:
```
   RsaSha256FulfillmentPayload ::= SEQUENCE {
     modulus OCTET STRING (SIZE(128..512)),
     signature OCTET STRING (SIZE(128..512))
   }
```

**Comment by JoelKatz** [comment]
At the moment, you pretty much have to use an empty message. You must either never re-use a public key for two conditions or use a different prefix for every payment and ensure the prefix is a parent condition.
The problem is that you have to worry that someone might find a way to satisfy your condition with a message you didn't expect. There are several ways you can avoid this, but it's kind of annoying that you can't really use the message nor can you ignore it.

**Comment by nbougalis** [comment]
@JoelKatz There's another problem that my suggest fixes.

Consider this example: Yes, this requires using a message, but the result is that a broken invariant: namely that given two fulfillments `F1` and `F2` and their respective conditions, `C1` and `C2` then, `C1 == C2 ⇔ F1 == F2`.

Here's the example:

```
std::array<std::uint8_t, 3> abc = { 'a', 'b', 'c' };
std::array<std::uint8_t, 3> def = { 'd', 'e', 'f' };

std::array<std::uint8_t, 32> sk =
{{
    // whatever
}};

prefix_sha256_t pf1;
pf1.setPrefix(makeSlice(abc));
pf1.setSubfulfillment (
    std::make_unique<ed25519_t>(SecretKey{ sk }, makeSlice(abc)));

prefix_sha256_t pf2;
pf2.setPrefix(makeSlice(abc));
pf2.setSubfulfillment (
    std::make_unique<ed25519_t>(SecretKey{ sk }, makeSlice(def)));

std::cerr << "pf1 f: " << to_string (pf1) << "\n";
std::cerr << "pf1 c: " << to_string (pf1.condition()) << "\n";

std::cerr << "pf2 f: " << to_string (pf2) << "\n";
std::cerr << "pf2 c: " << to_string (pf2.condition()) << "\n";

if (pf1.condition() == pf2.condition())
    std::cout << "pf1 and pf2 have the same condition!\n";
```

Guess what this program prints? Two entirely distinct fulfillments (`"abcabc"` and `"abcdef"`) share the same condition. Yes, I did reuse a prefix (which, as you point out, I can't do under the current implementation) but either way this is a problem. How?

Consider, for example, what happens if you track all your fulfillments in a map keyed by the condition. You've generated the above two fulfillments. Eventually, you decide you want to complete one of them. You look up `cc:1:25:9jvVAf67N8rbL5kDzVl2UOfmZvMuRtUlBDu5ezHOqp8:100` in your map. You get back the wrong fulfillment, and... oops?! What now?

Using the hashing approach I am suggesting would make this problem go away, it would be so improbable for two fulfillments to generate the same condition as to be effectively impossible.

**Comment by justmoon** [comment]
This got cleared up during the last community group call.

The explanation is that crypto-conditions are generally a type of signature scheme, so you wouldn't want conditions (i.e. public keys) to depend on the message.

The way we're using it in ILP is as a trigger mechanism where the message is empty. This is fine, it just means you always have to wrap the condition representing the public key (e.g. a Ed25519 condition) in a prefix condition to specify which message should be used as the trigger.

**Comment by adrianhopebailie** [comment]
> This is fine, it just means you always have to wrap the condition representing the public key (e.g. a Ed25519 condition) in a prefix condition to specify which message should be used as the trigger.

To be clear, you don't HAVE to wrap the ed25519 and RSA conditions in a prefix condition but if you don't then you have to generate a new key pair for each trigger.

By using the prefix you can reuse the same key pair and simply change the prefix and you'll have a unique condition fingerprint each time.
