### ISSUE TITLE
RFC-4: Property `data` on `Transfer` should be `ilpHeader` and `extraHeaders`

### ISSUE THREAD

**Issue by justmoon** [interledger/rfcs#127]
Currently the ledger plugin API docs say that the `data` on a `Transfer` should be a `Buffer`, in the implementation however, it is an `Object`.

This is a symptom of a different problem. The encoding of the packet according to our latest thinking is up to the plugin. As a result, the API between the host and the plugin should give the ILP header as a JavaScript object and let the plugin figure out the encoding.

In addition to the ILP header, the user may want to communicate a number of other `extraHeaders`, see [  ](https://gist.github.com/justmoon/5c2514af2eea06c9c58419520fe0b78c).      ,            .

**Comment by emschwartz** [comment]
If we formalize the ILP packet JSON (https://github.com/interledger/rfcs/issues/137), what do you think about just changing the field name from `data` to `ilp`, `interledger`, or `packet`? It seems odd to have separate fields for the ILP header and others.

**Comment by adrianhopebailie** [comment]
There is a separation of concerns issue here.

The interface exposed by plugins should offer both, a place to specify the ILP Header for the transfer and also "any other data". It is then the job of the plugin to encode these appropriately for the ledger which has no concept of ILP Headers.

In the case of the five-bells-ledger that would mean encoding as JSON and sending as a memo for the transfer but there could be a multitude of ways this is done with other ledgers. The minimum requirement for a plugin is: put this somewhere that the receiver is guaranteed to find it and be able to decode it.

Some ledger's will have a memo field, other will have other fields this can be put into. Some ledgers may not support this at all and the adaptor may need to communicate directly with the receiver out of band of the ledger to send this data and associate it with a transfer on the ledger.

Also, the `any other data` should have a `mime-type` or similar so we can leverage the flexibility of JSON (which can just embed other JSON seamlessly) but also support other encodings that may be more desirable for other interfaces. (Same applies for messages...)

Here's how I'd imagine the RFC changing to describe a Transfer object:

| Type | Name | Description |
|:--|:--|:--|
| `String` | id | UUID used as an external identifier |
| `String` | from | ILP Address of the source account |
| `String` | to | ILP Address of the destination account |
| `String` | amount | Decimal transfer amount |
| `ILP Header` | ilpHeader | ILP header send with the transfer |
| `Buffer` | data | Data packet or memo to be sent with the transfer |
| `Buffer` | noteToSelf | Host-provided memo that should be stored with the transfer |
| `String` | executionCondition | Cryptographic hold condition |
| `String` | expiresAt | Expiry time of the cryptographic hold |

Note: I dropped ledger from this object. Is there a need to specify the ledger if the plugin is only connected to a single ledger? Seems redundant if the plugin itself has a `getPrefix()` method.

**Comment by emschwartz** [comment]
I think we should keep the parts of the ILP packet together and we should define how to encode it in a variety of formats. For the JSON representation I'm fine with something like https://github.com/interledger/rfcs/issues/137 or https://gist.github.com/justmoon/5c2514af2eea06c9c58419520fe0b78c but I really want us to decide and properly write up the spec. If we have a good representation of the packet, I don't see the reason for having a separate `ilpHeader` and `data` field.

**Comment by adrianhopebailie** [comment]
> I think we should keep the parts of the ILP packet together

Why? It's easier for plugins to put things together than take them apart.

> we should define how to encode it in a variety of formats

That's only necessary if you put them together. If you don't then encoding is only a concern of the plugin. For example, for plugins written in Javascript the ilp header can always be provided in JSON and for Java adaptors they can use a strongly typed data structure using Java interfaces and objects. The *other data* can be more flexible but unless we know what that other data is then simply defining it as a binary blob (byte array in Java or Buffer in JS) is enough.

Assembling and encoding is the job of the plugin because it knows what it can pass through the ledger.

> If we have a good representation of the packet, I don't see the reason for having a separate ilpHeader and data field.

The reason is that we can't (and don't want to?) be specific about what is in the packet, only what's in the header.

**Comment by emschwartz** [comment]
Ok, I agree that the plugin should return a data structure that makes sense for the language (i.e. a class for OO languages, maybe JSON for Javascript). But I think that structure should represent the whole ILP packet, not just the ILP header.

In most cases I would expect the packet to be comprised of:
- ILP details: version, amount, account
- 1 (well-known) "transport layer" header, such as a Payment Request
- 1-2 routing-related headers (maybe)
- headers carrying application data

Implementations of the ILP packet class/parser should aim to support as many of the common header types as possible. Unknown headers would need to be dumped into a place where the raw data could be accessed like you say, but that should be part of the ILP Packet object.

I would propose something like this for Javascript:

```js
{
  version: 1,
  destinationAccount: 'us.usd.wf.bob',
  destinationAmount: '10.25',
  paymentRequest: {
    id: '5fe84ac7-5173-4ebf-8ddc-304937ad2450',
    expiresAt: '2017-01-05T14:12:39Z'
  },
  tailRoutingTags: {
    // not sure what actually goes here
  },
  otherHeaders: [{
    type: 'https://json-schemas.example/some-header-standard',
    mimeType: 'json',
    data: {
      foo: 'bar'
    }
  }, {
    type: 'https://blah.example/other-header',
    mimeType: 'application/octet-stream',
    data: <Buffer 01...>
  }]
}
```

**Comment by emschwartz** [comment]
This discussion is superseded by https://github.com/interledger/rfcs/issues/146. We are going to have an ILP packet that will include the extra headers and will be transmitted as part of the transfer memo field.

On the ledger plugin level we should decide whether the ILP packet will go in the memo. I would suggest putting it under a key like `ilp`.
