### ISSUE TITLE
RFC-8: Should this use JSON-RPC 2?

### ISSUE THREAD

**Issue by sharafian** [interledger/rfcs#136]
I think that using JSON RPC would make more sense than the format RFC-8 is using. For one, it has its own thorough specification, so we don't need to specify an entire RPC protocol just to specify one method (`quote_request`).

Secondly, JSON RPC has a better separation between methods, responses, and errors. Instead of responding to an RPC call (`quote_request`) with another RPC call (`quote_response`), JSON RPC would respond to a method call (`quote_request`) with a response object. If there was an error, the response will contain an `error` field (instead of using a third method, `error`).

Finally, JSON RPC is pretty widely supported, so there is more support in other languages.

I seem to remember JSON RPC being discussed at some point, so remind me if there was a reason we decided not to use it for this.

**Comment by sharafian** [comment]
also, it might make sense to separate quote by source amount and quote by destination amount into two methods, rather than making that implicit in the parameters.

**Comment by sentientwaffle** [comment]
So, to double-check: a quote request should look like this instead?

``` javascript
{
  jsonrpc: '2.0',
  id: 123
  method: 'send_message',
  params: {
    ledger: ‥
    from: ‥
    to: ‥
    data: {
      jsonrpc: '2.0',
      id: 456
      method: 'quote_by_source_amount',
      params: { source_ledger, source_amount, ‥ }
    }
  }
}
```

And a quote response:
``` javascript
{
  jsonrpc: '2.0',
  id: 123
  method: 'send_message',
  params: {
    ledger: ‥
    from: ‥
    to: ‥
    data: {
      jsonrpc: '2.0',
      id: 456
      result: { source_ledger, source_amount, destination_amount, ‥ }
    }
  }
}
```

**Comment by sharafian** [comment]
@sentientwaffle I agree that this looks a little convoluted due to the nested structure, but I think it's the best way to format it in our current system. It's not redundant because the outer JSON RPC request is still an RPC call to the ledger, but the inner one is an RPC call to the other connector.

If there were a way we could do this in a single connector-to-connector request-response (like when we did HTTP before) we could make this a little less bulky, but it doesn't seem like the ledger messaging facilitates that very well.

**Comment by emschwartz** [comment]
The option would be to change the ledger messaging to provide request/response functionality so that protocols built on top of it don't need to implement that themselves

**Comment by sharafian** [comment]
I think that would be a really strange and specific function for a ledger to offer.

**Comment by adrianhopebailie** [comment]
We should look at the messaging functionalit of the ledger as "just another transport". The fact that one ledger offers messaging through JSON RPC doesn't mean another will.

So, if we say that RFC-8 uses JSON RPC that only causes nesting if the ledger also uses JSON RPC for it's messaging transport.

I agree with @sharafian that using a standard like JSON RPC makes sense.

**Comment by adrianhopebailie** [comment]
Having looked at this in more detail I'm not sure ILQP should be dealing with message integrity at all.

If it is important to match a quote request with the response then put the id directly in the request and response objects.

Leave functionality like matching messages to the message layer.

A quote request should look like this:

```
{
  "id": "721e4126-98a1-4974-b35a-8a8f4655f934",
  "source_amount": "100.25",
  "source_address": "example.eur-ledger.alice",
  "destination_address": "example.usd-ledger.bob",
  "source_expiry_duration": "6000",
  "destination_expiry_duration": "5"
}
```

What the current format does is it assumes that the quote request and response will be delivered over a specific transport/channel (which today looks like JSON RPC but isn't).

It does raise the question about where the message format for different messages sent via the ledger messaging channel should be defined. Assuming this channel is intended for account holders (connectors or clients) to exchange messages what other messages might be sent via this channel? Are quotes the only message type? If so, should the Common Ledger Interface interface be less abstract and offer a `getQuoteFromConnector` function?

**Comment by adrianhopebailie** [comment]
Another thought is that the `quote_request` and `quote_response` should be extensions of a base `connector_message` format, which could be JSON RPC.

That would mean the format proposed by @sharafian would be correct but it has a clear separation of concerns.

This still means we can end up with JSON RPC within JSON RPC though so perhaps we need to think a bit about how the ledger messaging works so that we don't need to wrap things in so many layers.

**Comment by emschwartz** [comment]
Quoting and route broadcasts are going to switch to the binary format when that is finalized
