### ISSUE TITLE
RFC-3: Formalize the JSON format

### ISSUE THREAD

**Issue by sharafian** [interledger/rfcs#137]
(with @emschwartz )

We're using JSON for the ILP packet (for the time being), so we should better specify the format that that JSON will follow. Right now, the de-facto format seems to be:

```js
{
  "ilp_header": {
    "amount": "10.00",
    "address": "us.bank1.bob",
    "data": {
      // additional data here
    }
  }
}
```

In JSON, it seems like it would make more sense to have each header in the ILP packet be its own key in a map, instead of endlessly nesting them like you would in a binary format.

A proposal for this more understandable JSON format:

```js
{
  "ilp": { // saying "ilp_header" is redundant
    "amount": "10.00",
    "address": "us.bank1.bob"
  },
  "some_other": { // other headers are on the same level as ILP
    "time": "2016-12-27T15:42:22.132Z"
  }
}
```

The key that a header is stored under represents the header type. Every value is a JSON object, but it may have any fields inside.

To adhere to this protocol, connectors must forward the packet with all headers intact, including the ones they don't understand (unless adhering to a header's protocol means removing it).

**Comment by emschwartz** [comment]
Since this is the ILP packet it might be unnecessary to put ILP-related details under an `ilp` key. It could instead look something like:

```json
{
  "amount": "10.00",
  "account": "us.bank1.bob",
  "payment_request": {
    "id": "3e7a6fc5-eee4-451c-b3aa-fe6aa6390e51",
    "expires_at": "2017...",
    "memo": "This is for that thing"
  }
}
```

or even:

```json
{
  "amount": "10.00",
  "account": "us.bank1.bob",
  "request_id": "3e7a6fc5-eee4-451c-b3aa-fe6aa6390e51",
  "request_expires_at": "2017...",
  "memo": "This is for that thing"
}
```

On another note, should we include a version number in the packet?

**Comment by emschwartz** [comment]
I was playing around with Protocol Buffers last night to see what the developer experience would be like using that as a binary format for the packet.

One thing that stood out to me is the [canonical JSON encoding](https://developers.google.com/protocol-buffers/docs/proto3#json). What do you think about keeping the JSON version of the packet and (in the future if we don't need it now) having a binary version with a 1-to-1 mapping using something like protobufs if or when we need the more efficient encoding?

@justmoon I know you looked into different encoding formats at some point. What was your assessment of protobufs? It's not standardized by a proper standards body, but if it is only one of multiple supported encoding formats for our packet that might not be such an issue.

**Comment by sharafian** [comment]
Would the canonical JSON encoding of a protobuf ILP packet come out in the deeply nested format we have now? A good JSON format and a good protobuf format would probably be designed differently, even if the two formats could be serialized to one another.

**Comment by emschwartz** [comment]
This is the protobuf definition I was playing around with:

```protobuf
// ILP Packet
syntax = "proto3";
package interledger;

import "google/protobuf/any.proto";
import "google/protobuf/timestamp.proto";

message Packet {
  required uint32 version = 1 [ default = 1 ];
  required string account = 2;
  required string amount = 3;
  repeated Header headers = 4;
}

message Header {
  // TODO: do we need a HeaderType? or can it figure out which header it is based on the protobuf tags?
  optional bool ignore_unknown = 1 [ default = true ];
  oneof value {
    google.protobuf.Any custom = 2;
    PaymentRequestHeader payment_request = 3;
  }
}

message PaymentRequestHeader {
  required string id = 1;
  optional google.protobuf.Timestamp expires_at = 2; // TODO: use google.protobuf.Timestamp
  optional string memo = 3;
  optional string condition = 4;
}
```

Which would produce a JSON format that looks like:

```json
{
  "version": 1,
  "account": "us.usd.wf.bob",
  "amount": "10",
  "headers": [
    {
      "paymentRequest": {
        "id": "12345",
        "expiresAt": {
          "seconds": {
            "low": 1483030005,
            "high": 0,
            "unsigned": false
          }
        },
        "memo": "hi there"
      }
    },
    {
      "custom": {
        "type_url": "https://example.com/blah",
        "value": {
          "type": "Buffer",
          "data": [
            155,
            39,
            46,
            178,
            218,
            38,
            133,
            230,
            157,
            122
          ]
        }
      }
    }
  ]
}
```

I think this is pretty similar to what we would want from the JSON format.

One thing is that we would want to make our JSON representation use camelCase instead of snake_case.

In both formats we could make the additional header types either an array or keys on the same `Packet` message. The main decision there I think is whether we want headers to carry some extra information like the `ignore_unknown` value that's in there now, and whether we want to support having multiple headers of the same type in one packet. I _think_ an array is better than having all the other headers as keys on the `Packet` message.

**Comment by emschwartz** [comment]
Superseded by https://github.com/interledger/rfcs/issues/146
