### ISSUE TITLE
RFC 4: Use Common Ledger API Transfer object instead of separate Transfer abstraction

### ISSUE THREAD

**Issue by emschwartz** [interledger/rfcs#139]
(with @sharafian)

We have too many data formats that contain pretty much the same data but with slightly different field names and JSON hierarchies. 

If we are coming up with a ["Common Ledger API"](https://github.com/interledger/rfcs/pull/125) and devising the data structures ourselves, we should not need a separate abstraction layer on top of our own structure. Ledger plugins should instead be set up to use the same Transfer object as the Common Ledger API. Ledgers that do use the API we want already wouldn't need a real abstraction on top of them, and the purpose of the plugins would be to make other ledgers' transfers look like the format we like.

**Comment by adrianhopebailie** [comment]
There are two aspects to the abstraction though, the data model and encoding.

If the Common Ledger API is a REST API it defines encoding and data model contracts. While it's pretty trivial to represent a data model across many platforms the complexity comes from the encoding.

As an example, for the Java impl we've got a bunch of interfaces that define the various business objects (models) that a client expects to exchange with a plugin (we call it an adaptor). Even if that model is identical to the model used by the underlying ledger (i.e. no data transformations are required) the plugin/adaptor still needs to contain logic around how to encode/decode the messages to/from the ledger.

One solution is to define a Common Ledger API that does not have an encoding contract, only data models. In other words it is slightly more abstract than what is currently defined.

On top of that we can provide definitions of more specific interfaces that include the encoding contract (like REST or protobuf or others).

=================

My expectation of our process has always been that we will develop the various components using Javascript and JSON for speed of delivery and when the designs settle down would abstract out the data models in a non-platform specific form.

My attempt to do that is the

**Comment by emschwartz** [comment]
Don't think this is a good idea anymore
