### ISSUE TITLE
RFC-4: meaning of `p`

### ISSUE THREAD

**Issue by diminator** [interledger/rfcs#14]
In the method list like [connect](https://github.com/interledger/rfcs/blob/master/0004-ledger-plugin-interface/0004-ledger-plugin-interface.md#connect) it is described as `p.connect()`

My understanding is that `p` refers to the `LederPlugin` object and it has to interface all the listed methods. Is this correct?

**Comment by emschwartz** [comment]
Fixed by https://github.com/interledger/rfcs/pull/15
