### ISSUE TITLE
RFC-2: propose to migrate to RFCs and IDs repo

### ISSUE THREAD

**Issue by adrianhopebailie** [interledger/rfcs#148]
Having all of the ILP specs in one place has value but as specs mature and we push them out to standards bodies like IETF I propose we migrate them to https://github.com/rfcs/

We have already got https://github.com/rfcs/crypto-conditions which contains the ASN.1 and the test vectors, I propose we add the spec itself and the grunt scripts to generate the RFC text.

This will also allow us to easily tag the repo at a point when the draft is aligned with what has been submitted to the relevant standards body (in this case draft-02 of the Crypto-conditions spec).

It is becoming increasingly important to be able to version these specs and having one per repo makes this a lot easier (especially if they are not dependent on each other)

This would mean closing the two pending PRs and re-opening them at the new repo:
 - https://github.com/interledger/rfcs/pull/142
 - https://github.com/interledger/rfcs/pull/147

**Comment by emschwartz** [comment]
Addressed by https://github.com/interledger/rfcs/pull/164
