### ISSUE TITLE
'ping' message method

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#167]
I couldn't find the documentation for this, but it seems that messages that ilp nodes will send using the `sendMessage` method of the plugin interface, will always have a 'method' field, with a value of `quote_request`, `quote_response`, `route_broadcast`, or `error` (maybe I missed some other allowed values).

Anyway, my question is, would it be an idea to add a `ping` / `pong` message methods? I find myself using `quote_request` / `quote_response` for this purpose.

**Comment by michielbdejong** [comment]
so the purpose would be to check if a message recipient is currently listening/responding to incoming messages, and also what the roundtrip delay is.

**Comment by michielbdejong** [comment]
It would also be good if the 'pong' message would allow a ledger-user to for instance announce "I am a connector, and my API version is `ilp-connector@16`".

**Comment by emschwartz** [comment]
Can this be closed now?
