### ISSUE TITLE
support for temporary ledgers?

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#171]
The [ILP addresses spec](https://github.com/interledger/rfcs/blob/master/0015-ilp-addresses/0015-ilp-addresses.md) defines global, private, example, peer, test, self, and development prefixes, but maybe we can also define a `tmp.` prefix, to be used in market-making. You announce a temporary ledger to your peers, giving each peer an appropriate liquidity curve. Then try to get a quote to it from one of your other peers. The fact that the ILP address starts with `tmp.` indicates that it will only be used shortly after it was first announced, and can be dropped from routing tables again after, say, 10 minutes.

**Comment by emschwartz** [comment]
I don't think this is a good idea. If you just want to send a payment to yourself you can just do that with two accounts or with source routing (to be defined). As a connector, why would I want to store an entry in my routing tables that I know is supposed to disappear shortly thereafter. Seems like a good way to spam the network too.

**Comment by michielbdejong** [comment]
Openly admitting that your ledger is temporary, by including 'tmp' somewhere in the name gives connectors a way to choose whether they want to store your route, so it's less spammy than not providing such an indication.

But we can wait and see if people use this in practice. If they do, they can for now just use any prefix under `g.`. If they wanted to pick a descriptive prefix, they could even squat the `g.tmp.` neighborhood, without regulation. :)

Will reopen if/when temporary ledgers are seen in the wild.
