### ISSUE TITLE
PSK - AES/GCM requirements clarification

### ISSUE THREAD

**Issue by andrew-g-za** [interledger/rfcs#187]
Hi there,

The PSK RFC specifices that AES-256-GCM be used if encryption is chosen, and that if used the authentication tag must be written in the public Encryption header.

Could you please clarify
- what padding mode should be used when encrypting the private data (eg none, PKCS5Padding etc)?
- what tag length should be used?
- in what format should the tag be written in the header (base64, ASCII HEX etc)?

For reference, the Java implementation mentions that several tag sizes are available: "The GCM specification states that tLen may only have the values {128, 120, 112, 104, 96}, or {64, 32} for certain applications.",
see [GCMParameterSpec Javadoc](http://docs.oracle.com/javase/8/docs/api/javax/crypto/spec/GCMParameterSpec.html)

**Comment by sharafian** [comment]
We're using a tag length of 16 bytes, which is formatted into base64url when it's put into the encryption header. The padding mode used is PKCS.

**Comment by andrew-g-za** [comment]
Awesome, thanks!
