### ISSUE TITLE
Move InterledgerProtocolError to its own file and reuse for all protocols

### ISSUE THREAD

**Issue by earizon** [interledger/rfcs#194]
I think InterledgerProtocolError can be reused for any protocol, not just InterledgerPaymentProtocol, maybe just adding an extra letter-prefix to the error code indicating the protocol. This way all protocols can use the same exception mechanism / error control patterns with easy.

**Comment by emschwartz** [comment]
`InterledgerProtocolError`s are replaced by `IlpReject` in https://github.com/interledger/rfcs/pull/361
