### ISSUE TITLE
Put versioning information in RFCs

### ISSUE THREAD

**Issue by adrianhopebailie** [interledger/rfcs#201]
As implementations are being built of the various RFCs there is a need to reference the RFCs and specifically which version has been implemented.

## Proposal
* Add version meta-data to each RFC.
* Generate a versioned HTML file: `<version>.html` if one doesn't exist.
* If `<version>.html` exists then fail the build as the doc has changed and the version number should be updated.
* Copy `<version>.html` to `index.html` for latest version.
* Add a list of links to previous versions.

**Comment by michielbdejong** [comment]
In step 3, only fail of `<version>.html` exists and is different. Building the master branch with (some) docs that didn't change should work.
In step 4, we can have extra flexibility with a separate config file that specifies which version is currently live; then, future versions can already by committed to master, and we don't break the docs everytime someone merges a branch.
Then, in step 5, we can have links to previous *and future* versions! :)

**Comment by adrianhopebailie** [comment]
@michielbdejong I have started implementing, will get you to review later
