### ISSUE TITLE
Threshold Cryptoconditions Clarifications

### ISSUE THREAD

**Issue by nbougalis** [interledger/rfcs#209]
The existing specification of `THRESHOLD-SHA-256` can be somewhat confusing. 
 
The standard should be amended to explicitly define that each sub-entry in an M-of-N threshold is given a hard-coded weight of **exactly** 1, and that for a valid fulfillment, the number of subfulfillments present will be **exactly** `M`. This means that the threshold can be derived by counting the subfulfillments present.

Additionally, althought implicit (since the condition generated from such a fulfillment won't match) the standard should, **explicitly**, specify that a fulfillment that contains (a) a number of subfulfillments other than **exactly** `M`; or (b) one where the number of subfullfilments and subconditions present is not **exactly** `N` is not valid.

Far from a simple optimization to save space, not including the count and requiring exactly `M` fulfillments has a _valuable cryptographic purpose_: to _prevent malleability attacks_. This is not mentioned anywhere. For completeness and as a precaution against an accidental future change that would compromise this critical property, we should add a paragraph or note that explains the rationale behind this.

To clarify, consider a 3-of-5 condition. Now, assume a fufillment for that condition is presented that contains 4 subfulfillments and 1 subcondition. Such a fulfillment, if it were to be valid against the condition, would contain one redundant signature. Removing any one at random and replacing it with its subcondition would result in a different but still valid fulfillment.

**Comment by emschwartz** [comment]
Crypto conditions have moved to https://github.com/rfcs/crypto-conditions

**Comment by sappenin** [comment]
FYI, I created https://github.com/rfcs/crypto-conditions/issues/34 for tracking.
