### ISSUE TITLE
Alter PSK to use standard HTTP/S request

### ISSUE THREAD

**Issue by adrianhopebailie** [interledger/rfcs#215]
This is an alternative proposal to resolving #197 

Instead of inventing a new HTTP-like protocol we should simply use HTTP. The feature we are looking to add that is not in HTTP today is encryption and we can get this using TLS.

The data inside the ILP Packet should resemble one or more [TLS Records](https://en.wikipedia.org/wiki/Transport_Layer_Security#TLS_record).

[RFC4279](https://tools.ietf.org/html/rfc4279) defines TLS ciphersuites for use with pre-shared keys.

It should be possible to provide a TLS record that specifies the required crypto-params such as the ciphersuite, nonce and AES auth tag.

This can be followed by a TLS application protocol record that encapsulates an HTTP request with any application data in it.

**Comment by adrianhopebailie** [comment]
Propose that the `ilpPacket.data` contains two TLS Records; a ClientHello handshake protocol record and an application protocol record carrying the application layer data.

The ClientHello method structure is:
```
      struct {
          ProtocolVersion client_version;
          Random random;
          SessionID session_id;
          CipherSuite cipher_suites<2..2^16-2>;
          CompressionMethod compression_methods<1..2^8-1>;
          select (extensions_present) {
              case false:
                  struct {};
              case true:
                  Extension extensions<0..2^16-1>;
          };
      } ClientHello;
```
Where:
 * client_version = TLS 1.2 = {3,3}
 * random = `struct { uint32 gmt_unix_time; opaque random_bytes[28]; }`
 * session_id = null
 * cipher_suites = TLS_PSK_WITH_AES_256_GCM_SHA384 = {0x00,0xA9}
 * compression_methods = null

[AEAD Ciphers in TLS](https://tools.ietf.org/html/rfc5246#section-6.2.3.3)
[PSK Cipher Suites for TLS](https://tools.ietf.org/html/rfc4279)
[PSK Cipher Suites for TLS with SHA-256/384 and AES GCM](https://tools.ietf.org/html/rfc5487)

**Comment by emschwartz** [comment]
https://github.com/interledger/rfcs/pull/351 removes the HTTP-style headers and uses a simple binary encoding. Can we close this issue now?
