### ISSUE TITLE
Question - RFC8 ILQP terminology and quote routing

### ISSUE THREAD

**Issue by andrew-g-za** [interledger/rfcs#225]
Hi there,

I've been looking at RFC8 - ILQP and have a question about the terminology, and perhaps how that relates to routing quotes.

Importantly, the preamble of RFC8 defines various terms, particularly:

> The **receiver** is the party being credited at the end of the overall chain.
> The **destination** is the party being credited in a single link of the chain.
> 

The [IlqpBySourceRequest](https://github.com/interledger/rfcs/blob/master/0008-interledger-quoting-protocol/0008-interledger-quoting-protocol.md#ilqpbysourcerequest) defines the _destinationAccount_ field as [the] "Address corresponding to the **destination** account"

According to the terminology, this implies the account is a connector account (i.e a single hop in the chain), and **not** the final end receiver.

Is that correct? 
If so, for multi-hop routes, how would the quote propagate beyond the initial connector since there is no _receiver_ address to help connectors find the next link?

Confusingly, the spec frequently defines fields relating to a destination in terms of a receiver, for example in **IlqpBySourceResponse** the _destinationAmount_ field is defined as "Amount that will arrive at the **receiver**" - should the fields names (or descriptions) be updated to better match the terminology to avoid confusion?

**Comment by michielbdejong** [comment]
Oh, good catch, sorry you ran into that.

> The destination is the party being credited in a single link of the chain.

That's wrong, that party is called 'next', not 'destination'.  I already added [code comments](https://github.com/interledgerjs/ilp-routing/blob/2bd0bf35df99d64d70648ae2b018808ddd88ee0b/src/lib/routing-tables.js#L257-L266) about this in the ilp-routing code a couple of weeks ago, but I wasn't aware that the rfc was also affected - I'll create a PR to fix this!

**Comment by andrew-g-za** [comment]
Cool, thanks Michiel!

I'll close the question and await the PR.
