### ISSUE TITLE
0004: make Transfer#noteToSelf optional?

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#248]
It seems a bit weird to me that noteToSelf has to be set to `{}` if you don't use it.
I guess we could start adding support for `transfer.noteToSelf` being undefined to plugins, and then update the spec once all support this?

**Comment by emschwartz** [comment]
Where does it say it has to be set to `{}`? I don't think any plugins require it to be an empty object if you're not using it

**Comment by michielbdejong** [comment]
https://github.com/ripple/ilp-plugin-xrp-escrow/blob/master/src/plugin.js#L149 fails if you leave it undefined. We could also just say that it's a bug in that plugin. :)

**Comment by emschwartz** [comment]
I think that's more a bug in that plugin. But it could probably be made clearer that that field is optional

**Comment by sharafian** [comment]
Definitely just a bug in the plugin. Other plugins don't require that field.

**Comment by michielbdejong** [comment]
Done in https://github.com/interledger/rfcs/pull/304/files#diff-3f8c140769472860a18285c6e3ba39b2R478
