### ISSUE TITLE
PSK destination account has two wasted bits

### ISSUE THREAD

**Issue by dappelt** [interledger/rfcs#273]
I reimplemented the [PSK Shared Secret Generation](https://github.com/interledger/rfcs/blob/master/0016-pre-shared-key/0016-pre-shared-key.md#shared-secret-generation) recently and I noticed that two bits of the destination account are never used.

These are the instructions in question:
```
receiver_id = hmac_sha_256(receiver_secret, "ilp_psk_receiver_id").slice(0, 8)
destination_account = account + "." + base64url(receiver_id) + base64url(token)
```

The `receiver_id` has 8 bytes (or 64 bits)  and is base64url encoded. In base64, each digit represents 6 bits, so 64 bits are represented as 64 / 6 = 10.67 == 11 digits. Since 64 is not a multiple of 6, the last digit effectively represents only 4 bits.

To fix this small inefficiency, we could take the first 66 bits of `hmac_sha_256(receiver_secret, "ilp_psk_receiver_id")` instead of only 64 bits.

**Comment by adrianhopebailie** [comment]
> To fix this small inefficiency, we could take the first 66 bits of hmac_sha_256(receiver_secret, "ilp_psk_receiver_id") instead of only 64 bits.

This seems likely to be quite error prone. 

I agree that the current method is inefficient but really all we're doing with the base64url encoding is converting the `receiverid` into chars we can use in an ILP address.

We could use base16 (hex) encoding and be more efficient but end up with more (16) digits.

I guess the key question is: does the fact that the last few bits of the encoded receiverid are always the same present a security issue? I don't think so...

**Comment by dappelt** [comment]
This is not a security issue, but rather an inefficiency in the encoding of `destination_account`. There are two bits in `destination_account`, that don't serve any purpose and are always zero. So why not take them out? The only reason I see to not fix this is that it might be a breaking change.

>> To fix this small inefficiency, we could take the first 66 bits of hmac_sha_256(receiver_secret, "ilp_psk_receiver_id") instead of only 64 bits.

> This seems likely to be quite error prone.

Can you elaborate why it is error prone?

**Comment by sharafian** [comment]
I think the easiest fix would be using 24 bits (4 base64 characters) or 48 bits (8 base64 characters), because then they'll align with bytes. But I don't think it's so bad that we're wasting 2 bits here, so long as we can change this later without it being a breaking change

**Comment by adrianhopebailie** [comment]
> Can you elaborate why it is error prone?

Expecting people to start playing around with bits (i.e. not whole bytes) is usually dangerous as support for this is usually not great in any language.

I agree with @sharafian that if we want to use base64url encoding then we pick a size that's a multiple of 6 or just accept the inefficiency.

**Comment by dappelt** [comment]
Assuming you mean the number of bits for receiver_id should be a multiple of 6 **and** 8, I agree.
