### ISSUE TITLE
RFC-20 - Number of boxes passed to the connector

### ISSUE THREAD

**Issue by elmurci** [interledger/rfcs#277]
Shouldn't this bit:

_The USD ledger manager erases $10 USD from the senders account, puts $10 USD in the holding account, tells the connector about everything, keeps a box, and gives the connector the other two boxes._

Read:

_The USD ledger manager erases $10 USD from the senders account, puts $10 USD in the holding account, tells the connector about everything, keeps a box, and gives the connector the other **three** boxes._

?

**Comment by professorhantzen** [comment]
Yes - nice spotting. I’ve just submitted a PR that fixes that and clarifies the box handling a bit better. Cheers!

**Comment by adrianhopebailie** [comment]
Fixed in #278
