### ISSUE TITLE
[clp] Use packet.data.protocolData even if it's the only field in packet.data?

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#284]
Some clp calls have a field protocolData in addition to other fields (together in a sequence called data), but for Ack, Response, and Message, current master says packet.data should immediately be the protocol data, instead of a one-element sequence *containing* protocolData.

**Comment by dappelt** [comment]
Yes, that’s a pain. It would be nice if protocolData would always be in the same place. Otherwise you need ugly clue code to check first the type of the packet to know where the protocolData is.

**Comment by justmoon** [comment]
Note that a sequence of one element has the same encoding as that element. So this is a difference in the ASN.1 definition only, the code and the encoding would be the same either way.

**Comment by justmoon** [comment]
Example - wrapped:

``` asn1
World-Schema DEFINITIONS AUTOMATIC TAGS ::= 
BEGIN
  Human ::= SEQUENCE {
    name UTF8String
  }
END

first-man Human ::= {
  name "Adam"
}
```

In OER: `04416461 6D`

``` asn1
World-Schema DEFINITIONS AUTOMATIC TAGS ::= 
BEGIN
  Human ::= UTF8String
END

first-man Human ::=  "Adam"
```

In OER: `04416461 6D`

**Comment by michielbdejong** [comment]
Oh! ok, interesting. That's good news, then. We can still merge #285 and it will not affect the actual behavior. :)

**Comment by sappenin** [comment]
I think because, for example, making Response a `SEQUENCE` means it can have more than what's defined in `ProtocolData`, but for now doesn't change the encoding in ASN.1 binary.

**Comment by sharafian** [comment]
Yeah, it clarifies the ASN1 so that Message/Ack/Response don't look like special cases. As it is now, putting `::= protocoldata` is just syntactic sugar, but it can lead to a lot of confusion in implementations
