### ISSUE TITLE
Clarify Content-Type in SideProtocol Data

### ISSUE THREAD

**Issue by sappenin** [interledger/rfcs#286]
Continuation of discussion in  [#271 (comment)](https://github.com/interledger/rfcs/pull/271#discussion_r134353898)

@sappenin
> Can this just be an IA5String so we don't have CLP re-defining Content-Types?

@justmoon
> This field is intended to give applications that don't know/understand the custom protocol a way to at least partially decode the data. For example. we have values to indicate whether it's binary or text data. We intentionally want a small, defined list of supported formats here, NOT support any arbitrary mime type. If we want to add a format to the list, there should be broad agreement in the Interledger community that's it is worth adding this format to a large number of implementations. If the values in this field aren't widely understood the field is not useful.

> So I don't think we redefining anything - we're just defining a short list of mime types that are widely understood and since it's a small, standardized list, an enum is the correct type to use. I just realized that there is an ENUMERATED type in ASN.1 which would perhaps be an even better fit than INTEGER.
  
@sappenin
> Ok, perhaps I've been viewing this field a bit differently. I was thinking this content-type would be useful for applications that do understand the side-protocol...i.e., it gives those applications a mechanism to decode the data. For example, if I have a side-protocol named aml_protocol, then perhaps this payload is encoded as JSON, perhaps it's binary. Are you suggesting that if aml_protocol wants different encodings, then one should create separate protocolNames, like aml_protocol_json and aml_protocol_oer?

**Comment by michielbdejong** [comment]
We defined three content-types (octet stream, JSON, utf8), I think that's enough?

**Comment by emschwartz** [comment]
Can this be closed?

**Comment by sappenin** [comment]
I think so - my sense is that if we use HTTP in https://github.com/interledger/rfcs/pull/349 then we won't have to worry so much about side-protocol data definitions. They'll be much easier to pull-off simply by using HTTP.
