### ISSUE TITLE
[clp] should error responses be `Error`s or `Response`s?

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#290]
Ben says `Response`. I would say `Error`. We need to pick one.

**Comment by dappelt** [comment]
Assuming that the question is should an incoming  CLP `Error` be relayed to a peer as CLP `Error` or CLP `Response`, I think it should be relayed as `Response`. See also https://github.com/interledger/rfcs/pull/271#discussion_r133363793.

**Comment by michielbdejong** [comment]
@dappelt Your link to #271 doesn't seem to go to a specific comment.

I think it's pretty obvious that errors in response to unpaid requests should go into `Error` call types and not `Response`, just like errors in response to conditional requests should go into `Reject` call types and not `Fulfill`, otherwise it all becomes very messy.

**Comment by dappelt** [comment]
> @dappelt Your link to #271 doesn't seem to go to a specific comment.

github collapsed the specific comment when the page is loaded (we should try to avoid long discussions in a PR). This is the comment I am reffering to:

> > but then again we are expecting them to be relayed.

>I disagree. When an error occurs on the ledger layer, the connector should trigger its own error, because nobody else should have to care what ledger they are using. Put differently, the connector's error should look the same no matter what ledger was used.

> So if the ledger triggers L99 - AcmePay Is Not Feeling Like It, the connector should not relay it (as an L99) but rather it should emit its own T01 - Ledger Unreachable. They should feel free to include the ledger error in the freeform debug info if they want, because that doesn't force anyone to understand it.

**Comment by dappelt** [comment]
> I think it's pretty obvious that errors in response to unpaid requests should go into Error call types and not Response

It depends on why the error happened. If the error happened on the CLP-level (e.g. received packet is not valid CLP, unsupported side-protocol, etc.), then yes, it should reply with an `Error`. If the error happens because of some ILP-related functionality (e.g. F02 Unreachable), then it should reply with a `Response`.

**Comment by adrianhopebailie** [comment]
> In short, a CLP Error error indicates a problem with the local CLP link. Everything else should go into a CLP Response.

👍

**Comment by michielbdejong** [comment]
That would then not be symmetric with `Reject`, where `rejectionReason` can be either CLP-level or protocol-level. So then you would have to re-introduce the distinction between cancel (with rejectionReason) and reject (with just protocolData).

Funny how history repeats itself if you keep talking about these things long enough :)

**Comment by dappelt** [comment]
Can you give an example where `rejectionReason` would be CLP-level?

**Comment by michielbdejong** [comment]
There are a number of CLP-level reasons to immediately send an Error in response to a Prepare. The only situation where a Reject can be considered CLP-level instead of ILP-level is, I guess, when the expiresAt time has been reached? I guess we can also just let unfinalized transfer expires silently, then we don't need a special call for that, and then all we need to do is move the `rejectionReason` in Reject from the main fields into the ilp protocol data.

**Comment by sappenin** [comment]
Wondering if anyone can clarify this issue - if I look at the [ASN.1 definitions](https://github.com/interledger/rfcs/blob/1fb414215aed51965b695dba5c41e1daf2c577ea/asn1/CommonLedgerProtocol.asn#L62), the only thing in a CLP `Error` is an ILP Error packet ("rejectionReason").

In the case of a pure "CLP Error", what would be in the `Error` response? Presumptively, the "rejectionReason" would be empty, but then how does the receiver of the error tell what went wrong?

**Comment by sharafian** [comment]
The use of ILP Errors was more of a placeholder there while we thought of a more appropriate format for transmitting pure CLP errors. I've written a CLP-specific error format [here](https://github.com/interledger/rfcs/pull/291/commits/afcfe7985da0766a743336d61b4278cf6dfed3a4)

**Comment by michielbdejong** [comment]
Slight correction of the history books: It was not a placeholder, it was actually meant to be that way in the original version.

I'm not against changing it, but do take into account https://github.com/interledger/rfcs/issues/297 when you do.

**Comment by dappelt** [comment]
Closing this.

We decided that CLP-level errors will result in a CLP packet of type `Error`. Errors in higher-level protocols such as ILP or ILQP will result in a CLP packet of type `Response` and the sub-protocol carries the error.
