### ISSUE TITLE
[CLP]: Merge Error and Response Into a Single Object

### ISSUE THREAD

**Issue by sappenin** [interledger/rfcs#292]
Along the lines of #283, what if we also got rid of the `Error` response and just had a single response type that looked like this:

```
Response ::= SEQUENCE {
  error ErrorData OPTIONAL,
  protocolData ProtocolData
}
```

That way, there's only a single response that _may_ or _may not_ have an error in it.

**Comment by sappenin** [comment]
Actually, I think the ASN.1 definition would need to look like this (no `protocolData` in the error payload itself - that's always carried in the `Response`):

```
Error ::= SEQUENCE {
  rejectionReason InterledgerPacket, -- must contain an InternetProtocolError
}

Response ::= SEQUENCE {
  error ErrorData OPTIONAL,
  protocolData ProtocolData
}
```

An alternative encoding would be to make `ErrorData` a `SEQUENCE-OF-SEQUENCE` type so that we don't have to use the `OPTIONAL` semantics, like this:

```
Error ::= SEQUENCE OF SEQUENCE {
  rejectionReason InterledgerPacket, -- must contain an InternetProtocolError
}

Response ::= SEQUENCE {
  error ErrorData,
  protocolData ProtocolData
}
```

**Comment by sappenin** [comment]
This relates somewhat to #290, but is subtly different.

**Comment by dappelt** [comment]
Not convinced that we should merge the packet type `Error` and `Response`. Merging `Ack` and `Response` makes sense to me, since both indicate that a packet was succesfully processed. However, the same is not true for `Respone` and `Error`.

**Comment by sappenin** [comment]
Yes, I had a good conversation with @adrianhopebailie about this today and have changed my opinion -- am good keeping two packets, one for Response and one for Error. 

I'll close this issue - anyone feel free to re-open if desired.
