### ISSUE TITLE
[CLP]: Expand CLP to Apply to Non-Trustline Peering?

### ISSUE THREAD

**Issue by sappenin** [interledger/rfcs#293]
PR #291 says:

> CLP is a ledger protocol for bilateral liquidity relationships

If we were to add a `to` and `from` address into the CLP `prepareTransferRequest` payload, couldn't we also use this same protocol/flow/interaction model with non-trustline ledgers? For example, a ledger-abstraction that supports multiple accounts, like 5BL or something similar.

**Comment by justmoon** [comment]
Post-enlightenment we consider ledgers to be a type of connector. As such, they should derive the `to` from the ILP `destination`. Sure, some ledgers aren't going to be aware of ILP, but if they're implementing BTP clearly they've heard of us. So then they should just parse the destination.

The routing logic for such a node could be very simple: If the ILP address starts with the ledger prefix, forward it to that local account. If not, forward it to a connector. (Similar to the `connectors` field in 5BL.)
