### ISSUE TITLE
[CLP]: Don't use the term "packet" and "message" interchangeably in the RFC

### ISSUE THREAD

**Issue by dappelt** [interledger/rfcs#295]
The RFC uses CLP "packet" and "message" interchangeably. For example: 
> **CLP Packets** are the messages defined in the CLP ASN.1 spec ...

We should not use _packets_ and _messages_ synonymously in our CLP terminology. There is already a CLP packet type `Message`. Referring to the entire CLP packet as _the message_ will lead to ambiguities. In this sentence, I propose to use either _datagram_ or _unit of transfer_ instead of _messages_.

**Comment by adrianhopebailie** [comment]
Maybe we should use the term Protocol Data Unit (PDU)

**Comment by michielbdejong** [comment]
First time I hear that term. "PDU" is definitely less common than packet or message, and it's YAA. *)

In the sentence "The layer 3 (Network layer) PDU is the packet.", it's a term that is useful for talking about "what is the unit?", but I wouldn't use it as the *name* of that unit.

Just like people used to talk about the ECU, but when it became a reality, they named it the euro.

Let's just stick to "CLP packet" and "ILP packet".

---
YAA = "yet another abbreviation", autologically ;)

**Comment by dappelt** [comment]
Just to clarify, my concern is not to replace every occurrence of CLP packet with PDU. My concern is to not use the term _CLP packet_ and _message_ interchangeably.

I added a [commit](https://github.com/interledger/rfcs/commit/3f646a19adc8789f0cea065f8442fa903b80cd48) that updates the document accordingly. Let me know what you think.
