### ISSUE TITLE
CLP: Rename protocolData to subProtocolData

### ISSUE THREAD

**Issue by sappenin** [interledger/rfcs#296]
The usage of the term `protocolData` in various CLP Request objects is confusing because it's ambiguous if it's referring to CLP protocol data directly, or to the thing we've collogquially been calling "side protocol" data.

I propose that we rename this field to be `subProtocolData` so that it's clear it contains custom protocol data that is not formally part of CLP (other that the fact that it can go into this field).

Looking at PR #291, one of the heading sections uses the term "Sub-Protocol Data Format", but all of the ASN.1 examples just use `ProtocolData`.

**Comment by michielbdejong** [comment]
makes sense!

**Comment by michielbdejong** [comment]
I think since in BTP/1.0 it's called `protocolData`, and we introduced the distinction between primary and secondary, it's a bit late to still rename this now?
