### ISSUE TITLE
remove `rejectionReason` from `Reject` in BTP

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#297]
Now that `Error` [is only for BTP-level errors](https://github.com/interledger/rfcs/issues/290#issuecomment-329315612), and sub-protocol-level errors go in the appropriate protocolData field ('ilp' for ILP-errors, 'acme' for ACME-errors, etc.), we should do the same for `Reject`. There is no ledger-level reason to reject transfers, except for timeouts, which can be left implicit. When summing up the fulfilled transfers to determine the current balance just leave out any not-fulfilled transfer, including rejected ones and also once that never led to a reaction.

By removing https://github.com/interledger/rfcs/blob/1fb414215aed51965b695dba5c41e1daf2c577ea/asn1/CommonLedgerProtocol.asn#L63 we can put the ILP error inside the protocolData:

```js
packet = {
  type: BtpPacket.TYPE_REJECT,
  requestId: crypto.createRandomBytes(32),
  data: {
    protocolData: [
      {
        protocolName: 'ilp',
        contentType: BtpPacket.MIME_APPLICATION_OCTET_STRING,
        data: IlpPacket.serializeIlpError(...)
      }
    ]
  }
}
```

**Comment by dappelt** [comment]
@michielbdejong  Was this addressed? If yes, can you close it?

**Comment by michielbdejong** [comment]
yes, it was, in Ben's PR.
