### ISSUE TITLE
Proposal: Passive Payment Setup Protocol (alternative to SPSP)

### ISSUE THREAD

**Issue by emschwartz** [interledger/rfcs#30]
We've gotten feedback from a number of people that SPSP doesn't seem simple because it relies on direct communication between the sender and recipient, which can't be guaranteed in every scenario.

An alternative proposal: **Passive Payment Setup Protocol (PPSP)**

Sender gets the following from a static source (use-case specific, some kind of central registry):
* Ed25519 public key
* ILP Address
* Additional routing info needed by the sender (e.g. ledger precision)

PPSP would define how the sender should generate the condition from the transfer properties. The receiver would use the same method to check the incoming transfer against the condition before producing the fulfillment.

Open questions / issues:
* For SPSP we've been assuming that the receiver can tell the sender what the rate curve looks like from some more well-known ledger to final ledger. If there's no direct communication and the sender is only querying a static source, we need to figure out another way for the sender to determine the last mile rate. The sender could potentially send a quote request using https://github.com/interledger/rfcs/issues/29 before sending a payment.

**Comment by emschwartz** [comment]
cc @justmoon @adrianhopebailie @vhpoet @sentientwaffle

**Comment by adrianhopebailie** [comment]
> The sender could potentially send a quote request using #29 before sending a payment.

+1

> Ed25519 public key

How about just getting a condition (i.e. Don't limit it to a signature). The condition could have an expiry so it can be re-used or a flag that indicates it's a single use condition.

**Comment by emschwartz** [comment]
It might be useful later to define a protocol like this on top of the Passive Transport Protocol (mentioned in https://github.com/interledger/rfcs/issues/43), but closing this for now.
