### ISSUE TITLE
Cleanup BTP Error Codes

### ISSUE THREAD

**Issue by sappenin** [interledger/rfcs#301]
Looking at the [BTP error codes](https://github.com/interledger/rfcs/pull/291/files#diff-9310aac32ea1006a9786a37f8b4f79d7R383) a bit more closely, the current PR has some numeric errors and some apparent code duplication. I propose the following, which reduces the number of codes, improves error code naming (IMHO), and re-arranges the code numbers:

```
// A generic, unexpected exception returned by the ledger. This usually indicates a bug or unhandled error case.
T00: "Internal Error"

//The ledger request was syntactically invalid.
F00: "Request Not Accepted"

//The transferId included in the request does not reference an existing transfer
F01: "Transfer Not Found"

//The transferId included in the request matches a previous request, but other data does not.
F02: "Duplicate Transfer"

// The fulfillment included in the request does not match the transfer's condition.
F03: "Invalid Fulfillment"
    
// The transfer cannot be fulfilled because it has already been rejected or expired.
F04: "Transfer Rejected"

// The transfer cannot be rejected because it has already been fulfilled.
F05: "Transfer Fulfilled"

// The transfer cannot be prepared because there is not enough available liquidity.
F06: "Insufficient Liquidity"
```

**Comment by sharafian** [comment]
:+1: Those sound good to me, although I think there's some confusion around the first two:

```
// A generic, unexpected exception returned by the ledger. This usually indicates a bug or unhandled error case.
T00: "Internal Error"

//The ledger request was syntactically invalid.
F00: "Request Not Accepted"
```

`T00` in the current spec indicates something more along the lines of "heavy traffic" or " "currently unavailable, try again". `F00`, currently `NotAcceptedError` is closer to a 500, indicating that the request was semantically invalid. If the request is syntactically or structurally invalid, an `F01 InvalidFieldsError` should be returned. I think even if we change the names, its worth having a distinction between those three cases.

**Comment by michielbdejong** [comment]
Ah, alas, that spec is frozen now :) We can of course edit the text to clarify what things mean, but in BTP/1.0, at the time of the freeze, an F01 error clearly meant InvalidFieldsError and not "Transfer Not Found".

**Comment by dappelt** [comment]
> `T00` in the current spec indicates something more along the lines of "heavy traffic" or " "currently unavailable, try again".

That's confusing. An "Internal Error" should indicate that an unexpected exception happened, like @sappenin proposed. There should be separate errors for "heavy traffic" and "currently unavailable, try later".

**Comment by sharafian** [comment]
`T00` isn't an internal error though, it explicitly means "temporarily unreachable"

**Comment by sappenin** [comment]
@michielbdejong good point - perhaps we can consider this discussion for `v1.1` or whatever the next version will be?

@sharafian In my mind there doesn't seem to be much difference between `the request was semantically invalid` (currently `F00` in the [PR](https://github.com/interledger/rfcs/blob/726705c99d0324d352ab698eb618ae28d369eef1/00XX-bilateral-transfer-protocol/00XX-bilateral-transfer-protocol.md)) and `the request had invalid fields` (currently `F01` in the [PR](https://github.com/interledger/rfcs/blob/726705c99d0324d352ab698eb618ae28d369eef1/00XX-bilateral-transfer-protocol/00XX-bilateral-transfer-protocol.md)). In either case, this is an invalid request that will not ever be excepted, so I combined them into `F00` (above, which is roughly similar to an HTTP 400 Bad Request). Is there a good reason to be able to tell the difference in this case?

For the `T00` case, I was thinking the exact same as you -- something like a 503 in HTTP. interestingly, I've used HTTP 500 in the past to indicate "we have a bug in our server" and 503 to indicate something like, "we're overloaded", but in BTP it also feels like there's not a lot of value in telling the difference - both are temporary conditions that a client is unlikely to treat differently.

**Comment by sappenin** [comment]
Also, I'm re-thinking the name of `F04`: Perhaps "Transfer Cancelled" or "Rolled Back" instead of "Transfer Rejected"?

**Comment by adrianhopebailie** [comment]
@sharafian @michielbdejong @sappenin can we revisit this?

BTP 2.0 still has errors that no longer make sense like "Invalid Fulfillment".

**Comment by adrianhopebailie** [comment]
For BTP 2.0 I suggest we modify the codes to:

```
// A generic, unexpected exception. This usually indicates a bug or unhandled error case.
T00: "Internal Error"

//The ledger request was invalid (generic error).
F00: "Request Not Accepted"

//The syntax of the request was incorrect
F01: "Invalid Request"

//The request contained an unknown sub-protocol
F02: "Unknown sub-protocol"

//The message can't be processed as the session has not yet been authenticated
F03: "Request not Authorized"
    
//Another request is currently being processed with the same request id
F04: "Duplicate Request Id"

// The transfer is not accepted, the sender should not adjust their balances and manual intervention is likely required
F05: "Transfer Rejected"

```

If there is a desire to not re-use old codes then perhaps we can use "Pxx" for permanent errors and deprecate all "Fxx" codes?
