### ISSUE TITLE
Clarify how to recognize different error types in from LPI

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#302]
The way ilp-connector knows that a plugin throws one of https://github.com/interledger/rfcs/blob/master/0004-ledger-plugin-interface/0004-ledger-plugin-interface.md#errors is not by using `instanceof` because that would require shared JavaScript code between the plugin and the code that uses the plugin, or it would require the plugin to expose these error classes as constants. Instead, it [looks at `err.name`](https://github.com/interledgerjs/ilp-connector/blob/0697d37b65d2fcaa6aac42eb93871d96ae173530/src/lib/executeSourceTransfer.js#L75-L79).

I think it may be clear from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/name that an error object should have a `.name` field with its name, but if you look at for instance https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch and also how it's usually done in Java, C++, C#, etc. I think it doesn't hurt to add a sentence 'when catching an error, look for the `.name` field, which will then be the string from the left column in the table (case-sensitive)'

**Comment by emschwartz** [comment]
Can this be closed now that we're switching to LPIv2?

**Comment by michielbdejong** [comment]
It seems ILP v2 uses a mix of thrown errors and Promise rejections? And the PR description says "Clarify that errors should be distinguished by name", but I can't find that text, can you point to a line number?

**Comment by michielbdejong** [comment]
Github closed this.
