### ISSUE TITLE
Ideas for improving HTTP-ILP

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#307]
Compared to #306, I would propose to keep the current version as one flow, useful for one-off actions, and add a second flow, aimed more at streaming content. In this second flow, the server would not respond with a 402; instead it will respond with a 200, and then wait for a streaming payment to start, before streaming the content body. For this, I would make the following changes:

* make the [`PayToken` request header](https://github.com/interledger/rfcs/blob/ff6e28c45b51de3b4ecc61488ad16fe42e6190f0/0014-http-ilp/0014-http-ilp.md#21-client-attempts-to-call-api-using-token) optional (it's not needed in the streaming flow)
* make the [response code in case of insufficient balance](https://github.com/interledger/rfcs/blob/ff6e28c45b51de3b4ecc61488ad16fe42e6190f0/0014-http-ilp/0014-http-ilp.md#22-server-rejects-request-because-token-is-new-and-unfunded) a choice between 402 (for one-off services) and 200 (for streamed content)
* make the `Pay-Balance` header there optional, because it would always be zero if no token was sent.
* once a payment is fulfilled, the client only needs to [repeat its request](https://github.com/interledger/rfcs/blob/ff6e28c45b51de3b4ecc61488ad16fe42e6190f0/0014-http-ilp/0014-http-ilp.md#26-senderclient-receives-the-fulfillment) if it has previously received a 402. If it got a 200, the client doesn't have to do anything - body streaming will just start
* client could send more than one payment to continue the streaming. We would have to decide how the price indicated in the `Pay` header's Amount field works in this case (interpret it as a price per byte, maybe?)

**Comment by emschwartz** [comment]
> make the PayToken request header optional (it's not needed in the streaming flow)

How would the server correlate incoming payments with which client is sending them?

**Comment by michielbdejong** [comment]
the `Pay` token has an ILP address and a condition. Both can be used to identify the client.

**Comment by michielbdejong** [comment]
In the streaming-payments tutorial I added the `userId` to the `account` value of the PaymentPacket.

**Comment by emschwartz** [comment]
> the Pay token has an ILP address and a condition. Both can be used to identify the client.

These come from the server. How do clients identify themselves across multiple HTTP requests?

**Comment by michielbdejong** [comment]
> How do clients identify themselves across multiple HTTP requests?

If they want to do that, with `Pay-Token`, that doesn't change. But with this new HTTP-ILP "streaming mode", you could also just pay once, and use up all your balance all at once, then you don't need to identify yourself across multiple HTTP requests.

**Comment by michielbdejong** [comment]
cc @sharafian, @justmoon

**Comment by justmoon** [comment]
Can you build a sample implementation?

**Comment by michielbdejong** [comment]
yes, it's in https://github.com/interledger/tutorials/pull/2

**Comment by michielbdejong** [comment]
Merging this issue into #329
