### ISSUE TITLE
clarify how connectors can steal using InsufficientSourceAmount errors

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#321]
[IL-RFC-3 (draft 4)](https://interledger.org/rfcs/0003-interledger-protocol/draft-4.html#ilp-error-codes) mentions:

> R01 | Insufficient Source Amount | Either the sender did not send enough money or the exchange rate changed before the payment was prepared. The sender MAY try again with a higher amount, but they SHOULD NOT do this indefinitely or a malicious connector could steal money from them.

How would this stealing work? That's not clear to me from the text. As an implementer, I would be unsure how often a payment could safely be retried (not indefinitely, but how often then?), if I don't understand how this attack would work. Maybe link to a more elaborate description elsewhere?

**Comment by emschwartz** [comment]
Agreed that this could use more clarification.

Basically, you have to be careful with how much you're willing to increase the source amount. A sender might be unwilling to increase the source amount at all, though I would guess in many cases you would accept a bit higher cost to make it go through. 

If an implementation of a sending client were to increase the source amount automatically (without some maximum, or with a maximum that's higher than what the sender might like), you could end up accidentally sending away far too much money.

**Comment by michielbdejong** [comment]
Ah ok, then I would propose the text "If the sender is willing to pay more, they MAY try again with a higher amount".
