### ISSUE TITLE
Update TOC on website

### ISSUE THREAD

**Issue by adrianhopebailie** [interledger/rfcs#322]
Need to add some missing IL-RFCs to the TOC

**Comment by adrianhopebailie** [comment]
This is the current TOC:

- Interledger Architecture
- Interledger Protocol (ILP)
- Interledger Addresses
- Pre-Shared Key (PSK) Protocol
- Interledger Payment Request (IPR)
- Simple Payment Setup Protocol (SPSP)
- Javascript Ledger Plugin Interface
- W3C Web Payments Interledger Payment Method

I propose we at least add the HTLA and HTTP-ILP RFC's to this.

@michielbdejong @emschwartz @sharafian @dappelt @justmoon WDYT?

**Comment by emschwartz** [comment]
Sounds good, can you open an issue or PR on the website repo?
