### ISSUE TITLE
add destinationHoldDuration to IPR

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#327]
While implementing the [Interfaucet](https://github.com/interledgerjs/interfaucet), it occurred to me that an Interledger Payment Request is not really complete if it doesn't describe the destinationHoldDuration in the same way [QuoteByDestination](https://github.com/interledger/rfcs/blob/master/0008-interledger-quoting-protocol/0008-interledger-quoting-protocol.md#quotebydestinationrequest) does.

**Comment by adrianhopebailie** [comment]
No longer applicable with IPRv3 and ILPv4
