### ISSUE TITLE
clarify relation between ILP addresses and on-ledger address in LPI

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#328]
The [description of `Transfer#to` in the LPI](https://github.com/interledger/rfcs/blob/master/0004-ledger-plugin-interface/0004-ledger-plugin-interface.md#transferto) states that it needs to be "the ILP address" of the credit account. But that can be interpreted in two ways: If you pay to `g.ledger.account.some.other.identifiers`, then should this field contain that full string or just `g.ledger.account`?

I would argue for the latter, since the sender already needs to know what the ledger prefix is (it's one of the fields as well, and also you need to know which level the `amount` applies to). The transfer object instructs the ledger about which on-ledger account it goes to, and the other identifiers are only needed in the packet that describe the payment to the receiver.

**Comment by sharafian** [comment]
also because plugins like xrp-escrow and btp fill in the `to` and `from` fields from ledger layer data, the extra segments can't be included there.

**Comment by emschwartz** [comment]
Can this be closed now?

**Comment by michielbdejong** [comment]
I don't think it was fixed, was it? See https://github.com/interledger/rfcs/pull/341#issuecomment-352186733
