### ISSUE TITLE
RFC-3: Split error data and human-readable error metadata

### ISSUE THREAD

**Issue by justmoon** [interledger/rfcs#331]
In the future, we may want to pass back machine-readable information with certain errors, for an example, see: #318.

RFC-3 currently says rather vaguely about the `data` field:

> Error data provided primarily for debugging purposes. Systems that emit errors SHOULD include additional explanation or context about the issue.

We should split `data` in ILP Error into two separate fields. `data` for machine-readable error-specific data such as in #318 and `debugJson` for human-readable (JSON) data.

**Comment by emschwartz** [comment]
Resolved by https://github.com/interledger/rfcs/pull/355
