### ISSUE TITLE
RFC-4: Change RejectionMessage to match ILP (RFC-3)

### ISSUE THREAD

**Issue by justmoon** [interledger/rfcs#332]
There are a couple of issues with the RFC-4 [RejectionMessage](https://github.com/interledger/rfcs/blob/75d819d5947c6cee94510b7b1cd009e1627fc748/0004-ledger-plugin-interface/0004-ledger-plugin-interface.md#class-rejectionmessage):

* `forwarded_by` should be an array
* `message` does not exist in the ILP packet and should presumably move to `additional_info`

**Comment by michielbdejong** [comment]
This would break all existing plugins, right? What problems are caused by it currently not being an array?

**Comment by justmoon** [comment]
No, the plugins are *currently* broken, this would fix them. Forwarded by is an array in ILP, this is just a bug in the LPI that propagated to the plugins.

**Comment by michielbdejong** [comment]
Interesting! Reminds me of https://en.wikipedia.org/wiki/HTTP_referer#Etymology.

**Comment by emschwartz** [comment]
Given https://github.com/interledger/rfcs/pull/347, I think we can leave LPIv1 as it is and make sure to include these changes in v2

**Comment by emschwartz** [comment]
@justmoon can we close this?
