### ISSUE TITLE
when selling apples, embrace rejection

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#333]
One day, I found myself selling 1000 apples at the market. I deposited the apples at the auctioneer's desk, asked around to find buyers and get quotes, and when I got the best quote, I told the auctioneer to give the apples to that buyer at the agreed price. That night, I dreamed about ILQP.

The next day, it occurs to me that I had better sell the apples one by one. So I decide a minimum price per apple, tell this (in secret) to the auctioneer, and advertise the quality of my apples to potential buyers. They put in their bids, and if their bid is high enough, they can buy one apple. The buyers soon use binary search to find out which minimum price I told the auctioneer, and the rest of my apples all sell at that price within a few minutes. That night, I dreamed about ilp3.

The third day, it occurs to me that telling the auctioneer a minimum price was not ideal, because my apples sold quickly at the minimum price I had set. So this day, I tell the auctioneer to sell my apples to the highest bidders throughout the day. So the auctioneer now sells one apple per minute, only to the highest bidder that presented themselves during that minute. Each minute, buyers adjust their bid to what they think the others are bidding. That night, I dreamed about [FPSBAs](https://en.wikipedia.org/wiki/First-price_sealed-bid_auction).

The fourth day, I decide I don't want to stay at the market all day, if that's not necessary, so I tell the auctioneer to offer bulk discounts for people who are willing to buy more than one apple per minute (e.g. 1% off if you buy 10 at a time, 2% off if you buy 100 at a time, 3% off if you buy the whole lot). That night, in my dreams I turned into an sender; my apples converted into prepared source transfers, the auctioneer became a receiver, the buyers turned out to be connectors, and the price per apple was the destination amount. The Interledger network in my dream had a lot of rejected transfers; in fact, just like the auctioneer only accepted winning bids from the apple buyers, the receiver only accepted very few of the transfers that reached it - the vast majority of transfers were rejected. Everybody embraced the rejection of transfers as just a way to do auctions, and lived happily ever after.

**Comment by sappenin** [comment]
Amazing!

**Comment by emschwartz** [comment]
Can this issue be closed?
