### ISSUE TITLE
in psk, should hmac be taken once, or twice?

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#335]
One issue Ben and I resolved in our video call yesterday was me thinking the sender in PSK was free to choose any packet data they want (I now understand that PSK is not a just a way to derive a fulfillment from a packet, it also restricts the packet contents).

But apart from the restrictions on the packet, I thought the way psk works in terms of determining the fulfillment, was:

```js
fulfillment = hmac_sha_256(shared_secret, ilp_packet)
```

This seems to be also what the spec says at first ("it" at the end refers to the fulfillment):
> The sender creates the condition of their payment by taking the HMAC of the full ILP packet with the pre-shared secret key, and computing the SHA-256 hash of it.

But then later the spec that the hmac key is not the shared secret, but rather *derived* from it:
> The receiver fulfills the incoming transfer with the HMAC of the ILP packet, using the same HMAC key as the sender, derived from the shared secret.

And in the code snippets it indeed says that you need to derive a `fulfillment_generator` first, even though this is not at all mentioned in the spec text, it seem?:
```js
fulfillment_generator = hmac_sha_256(shared_secret, 'ilp_psk_condition')
fulfillment = hmac_sha_256(fulfillment_generator, ilp_packet)
condition = sha_256(fulfillment)
```

Which one is it?

I did notice that in the appendix there's a mention of deriving shared secrets from the receiver secret, and there, the hmac of the string 'ilp_psk_condition' is also taken, presumably to obtain a string of the right length, in case the receiver secret is longer or shorter than 32 bytes?

**Comment by dappelt** [comment]
Twice. 

If the same `shared_secret` is used throughout the code base to sign different things, it's good practice to derive a specific key at the different places it is used. This limits the scope for which a specific key is valid.

**Comment by michielbdejong** [comment]
If we want it to be twice instead of once, then we should change the phrase that says "The sender creates the condition of their payment by taking the HMAC of the full ILP packet with the pre-shared secret key, and computing the SHA-256 hash of it.", right?

I think what should happen is once you have the real psk `shared_secret`, you only hmac once with it, *but* in the (ilp-kit) code base that we describe, it's best practice to derive this `shared_secret` from another secret (the `receiver_secret`).
