### ISSUE TITLE
idea: propagating vouches

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#339]
The vouch protocol has so far only been described in the context of the Interledger Testnet of Testnets, but basically, it allows you to link an on-ledger account to a BTP account. Once you do that, you can pay your peer on-ledger and they will know it's you, but also, your peer can pay you on-ledger (you announce both the address you vouch for and the address on which you can be reached). However, route broadcasts, remote quoting, and other c2c messaging will still go over btp.

now, here comes the interesting point: if Alice announces a route to Bob, and Bob forwards this info to Charlie, then Bob doesn't necessarily have to add himself as a head-hop; if Alice's route starts over BTP, then Bob will make himself a headhop, but if the route starts e.g. on xrp ledger, then this is a way for the network of connectors to store-and-forward a list of connectors that exist on each crypto-currency ledger. i'll try to work this out in more detail.

**Comment by emschwartz** [comment]
Can this be closed now?

**Comment by michielbdejong** [comment]
Yes, [R.I.P. on-ledger transfers](https://www.slideshare.net/Interledger/34c3-interledger-presentation-background-streaming-payments-and-implications/57) :)
