### ISSUE TITLE
RFC-3: Proposal especify Ilpamount with integers

### ISSUE THREAD

**Issue by r-marques** [interledger/rfcs#34]
Specifying amounts in floating point can be prone to error specially for protocols designed to be interoperable between different implementations in different languages and running on different hardware.

I think that it would be possible to use only integer amounts in the interledger protocol. Different ledger implementations already do this by specifying the amounts in the minimum divisible units. In bitcoin transactions, amounts are specified in _satoshi_ and in ethereum transactions, amounts are specified in _wei_.

The same could be done in Ilp when requesting a quote from the connector the connector could provide information about the minimum divisible unit in the destination ledger. This way a client could specify integer Ilpamounts.

**Comment by emschwartz** [comment]
This was a very good suggestion that we should have adopted way earlier. It has now been included in https://github.com/interledger/rfcs/pull/163
