### ISSUE TITLE
Signed conditions or test payments?

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#345]
On Monday I floated a proposal to add a signature from either the destination ledger or the receiver, that tells connectors along the way that this condition is one that the receiver can fulfill, if it reaches the destination ledger. This would act as a protection against "unfulfillable payment spam" which can be used to trick both manual and automated route switching strategies, and divert traffic to a more expensive or less reliable route.

Yesterday, @emschwartz and I had a long video call where we compared this system to the option of adding a test payment protocol to for instance spsp.

Advantages of signed conditions:
* you don't need to generate extra test traffic on top of the main traffic
* using stats from the actual live traffic means you don't need to worry about Volkswagen strategies
* route switching can be linked to stats more directly, you can immediately react to measurements, instead of having to aggregate test results over time and react to them with a slight delay.

Advantages of test payments:
* you don't need to change how payments work
* you don't need to distribute public keys until the moment someone wants to test their connection to you

The idea of test payments added to Interledger by themselves would be just that the check/verify whether route broadcasts with curves are truthful, thus making truthfulness the dominant strategy. In practice, the threat of switching away from a route where test payments fail would hopefully be enough for everybody to broadcast truthful liquidity curves, and not try to blackhole traffic by announcing exchange rates that are too good to be true.

On top of these test payments, @emschwartz's ilp3 proposal would then also remove the amount from the packet, but I think that's a separate decision.

**Comment by michielbdejong** [comment]
If these lists of advantages of each is correct, then I would lean towards test payments, mainly because it would decouple the identity stuff from the actual payments, so that means we can iterate on how these test payments work without changing anything in the ilp packets of real payments.

**Comment by adrianhopebailie** [comment]
I am in favor of de-coupling the path finding/quoting from payments as much as possible. 

I think we will still end up with a need for some kind of quote request at the ledger layer but that is independent of how ILP works.

Strongly oppose adding anything that may require PKI into the ILP layer.

**Comment by michielbdejong** [comment]
Yes, the signatures should go on a higher layer than the hashlocks.

Actually, I think the best of both worlds would be for the receiver to add a payload signature to the result (error or fulfillment data). This can then be totally ignored on the interledger level, but if you happen to know the public keys of some receivers on a ledger, then as a sender or as an intermediate connector, you can use these to get more reliable stats.

**Comment by emschwartz** [comment]
Can this issue be closed now?

**Comment by michielbdejong** [comment]
yes, we decided in favour of test payments.
