### ISSUE TITLE
what benefit do delivered payments provide?

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#348]
Question asked by @emschwartz in Slack, will try to answer it here.

**Comment by michielbdejong** [comment]
So as a base line we take the situation where Alice wants to send 1 USD to Bob in a single chunk. She first does an end-to-end quote in an unfulfillable forwarded payment of 1 USD, and Bob rejects it, responding that 92 cents arrived.
She decides that that's good enough, and does the fulfillable forwarded payment of 1 USD. The path is determined at each connector by the results of test payments that each connector regularly does to Bob's ledger.

With delivered payments, Alice would first do a ILQP QuoteBySource request to find out that the destination amount for source amount 1 USD would be 92 cents, then decide that that's good enough, and do a fulfillable delivered payment with 1 USD source transfer amount and 92 cents packet amount. The path is determined by a combination of route broadcasts and remote quoting to obtain data, and test payments to verify whether that data is true.

One advantage is that instead of having to quote each payment end-to-end, connectors can use remote quoting and cache quote results. A further advantage over that is that liquidity curves can be included into route broadcasts, meaning price information is propagated through the network in a push instead of a pull fashion, which is algorithmically more efficient.

A third advantage is that to get the price information she might want, Alice could not only do QuoteBySource, but also do QuoteByDestination and QuoteLiquidity, things that are harder if not impossible in end-to-end quoting.

A fourth advantage is that if connectors announce a set price, they can be held to that promise, and in such direct competition, it will be harder for connectors to charge high fees. Remember that charging a high fee on a forwarded payment would work, within the margin of overpayment; in delivered payments, charging a high fee would immediately cause the payment to fail.

**Comment by emschwartz** [comment]
I don't think it makes sense to have a feature in the core interoperability layer that is _at best_ for intermediary data collection.

The original motivation for "delivery" was because we considered overpayment to be a bug. We realized that this type of consideration should be handled at the transport layer, so we should deprecate delivery and type 1 ILP packets (with the amount in the clear).

**Comment by michielbdejong** [comment]
What difference does it make if we rename `packet.amount` to `packet.data.amount`?

**Comment by michielbdejong** [comment]
If we didn't have the current ordering of fields with the OER-encoded packet inside `transfer.ilp` then I would say, sure, let's add a level of nesting/encapsulation for each concern.

But moving the amount into the packet data as you propose here, if at the same time we're moving the packet fields into the transfer as you propose elsewhere, would just be renaming `transfer.packet.amount` to `transfer.data.amount`. :D

Given that we have a working system, proposing to move things around every few weeks is destructive because it breaks the network, and at the same time it's labor-intensive because it keeps the whole community busy reimplementing things which we already have, so that hurts the project twice.

**Comment by adrianhopebailie** [comment]
> Given that we have a working system

But we don't. See https://github.com/emschwartz/ilp3/issues/12. There numerous issues with the current system. 

>proposing to move things around every few weeks is destructive because it breaks the network

"Moving things around" is trivializing the issue. Moving a data field up or down the protocol stack has a major impact. In this case we are removing amount from the interop layer which dramatically simplifies implementations of all intermediaries. We are adding it to the transport layer which changes the requirements of the transport layer. These are fundamental changes to how the protocol works. I think that in the issue above it's well documented why they are needed so the longer we wait to implement them the harder it will be.

As a general rule, anything that is not strictly related to simply moving money from A to B should be in the transport or application layer. That includes quoting and any other process that is related to execution of "business logic".

**Comment by emschwartz** [comment]
Can this issue be closed now?
