### ISSUE TITLE
Currency on simple-payment-setup-protocol Invoice 

### ISSUE THREAD

**Issue by rozzamozza** [interledger/rfcs#37]
There is am amount in the invoice protocol but no currency or currency code.
What's the policy/agreement re currencies. Shouldn't amounts always be accompanied by a currency?

**Comment by emschwartz** [comment]
In the Interledger model we say that a ledger is a system that tracks assets of one and only one type. Therefore, the currency is defined by the ledger. In some application layer protocols, the currency code or symbol may be included to be able to display it for the user, but it is not necessary for the core protocol.
