### ISSUE TITLE
Introduce eXtended Merkle Signature Scheme. (XMSS) as one of the cryptographic signing schemes for a post quantum world

### ISSUE THREAD

**Issue by nathanawmk** [interledger/rfcs#370]
Hi all,

I am proposing that we progressively introduce eXtended Merkle Signature Scheme (XMSS) in Interledger as one of the cryptographic signing schemes for a post quantum world.

Nathan Aw

**Comment by emschwartz** [comment]
Hi Nathan,

We actually decided a while back (https://github.com/interledger/rfcs/issues/153) that we would only use Sha256 hashlocks for Interledger conditions. As far as we understand it, Sha256 is expected to survive the shift to quantum. 

The Crypto Conditions work has moved [here](https://github.com/rfcs/crypto-conditions), but is no longer a dependency of Interledger.

**Comment by adrianhopebailie** [comment]
To be more explicit, a subnet of nodes on the public Interledger network could choose to adopt a more complex condition (like crypto-conditions) and depend on these for executing of the transfers just between themselves. This could include a condition that combines the ILP hash-lock with a notary signature for example (i.e. atomic mode ILP).

Also, with ILPv4, we have determined that conditional transfers (at the ledger layer) are a tool that is available for any two peers to use to secure the transfers between them, but are not a requirement for ILP.

**Comment by nathanawmk** [comment]
Understood. Thanks!
