### ISSUE TITLE
idea: multi-user payment channels

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#380]
You need to open a payment channel to your connector, but if you don't know up front which connector you will be using, it would make sense to open one payment channel to multiple connectors.

I would like to connect to multiple upstream connectors, but I don't want to earmark a specific chunk of my funds to each one of them. Therefore, it would be cool if I could write an Ethereum contract that will look like a regular payment channel to each of those ILP connectors, but I will only do one funding transaction, and I can share that channel funding among multiple recipients, so that I can postpone the decision of whom I will eventually pay how much.

**Comment by emschwartz** [comment]
When each one gets a claim from you, how do they know you haven't already committed the balance of the channel to one of the other connectors?

**Comment by michielbdejong** [comment]
Hm, good point! I guess you would need multiple signatures on the claim. So number of signatures needed is number of participants minus one. In the simple case, two participants, claims have only one signature.

**Comment by dappelt** [comment]
There is some [work](https://www.coindesk.com/lightning-scaling-bitcoin-might-require-whole-nother-layer/) on Lightning multi-party channels.

**Comment by emschwartz** [comment]
To me a multi-party payment channel just sounds like another ledger. I think it would probably be simpler to build a sidechain where transfers are fast and cheap so you can use them instead of payment channel claims.

**Comment by michielbdejong** [comment]
@emschwartz we probably mean the same thing :) I guess the simple view is if each participant 
has to sign each transaction. You could also do this in two layers, where you have several two-player channels connected to a central "pot", and transactions that cross the pot have to be signed by all stakeholders.

**Comment by adrianhopebailie** [comment]
@michielbdejong can this be closed

**Comment by michielbdejong** [comment]
@adrianhopebailie only if you found the solution ;)

**Comment by adrianhopebailie** [comment]
I interpreted your responses above as "I guess this isn't a good idea". Was I wrong?

**Comment by michielbdejong** [comment]
Yes, it might be a bit of an advanced topic and not highest priority for mvp, but I think if we would implement this, the advantages would be as described.
