### ISSUE TITLE
BTP protocol registry

### ISSUE THREAD

**Issue by michielbdejong** [interledger/rfcs#381]
As part of defining the testnet-18Q1 version of Interledger, I'm starting to investigate which `protocolName`s are used by https://github.com/interledgerjs/ilp-plugin-xrp-asym-client and https://github.com/interledgerjs/ilp-plugin-xrp-asym-server. So far, I thought I would just do this [on the wiki](https://github.com/interledger/interledger/wiki/Interledger-over-BTP#changes-between-versions-17q4-and-18q1) but I think it's useful if the wiki can just refer to an RFC version that describes the various `protocolName`s in more detail.

So far, the basic definition of testnet-18Q1 consists of:
* bottom layer is either http or WebSockets. For http, use POST to /protocolName. For WebSockets, use BTP Message / Response / Error calls. HTTP ILP-* request headers are still supported in 18Q1, but deprecated.
* For protocolName 'ilp': Forwarded Interledger payments, with sha256 hashlocks, Interledger destination addresses, no publicly readable destination amount in the prepare, and end-to-end data in the prepare, as well as in the fulfill and the reject (for reject, this data is generated wherever the error happens, and is publicly readable), encoded in Type-12/13/14 ilp-packets (raw OER goes in http post bodies, or inside BTP Message calls over WebSockets)
* 'auth', 'auth_username', 'auth_token' - described in the BTP rfc, could be different for http
* 'channel', 'fund_channel', 'channel_signature' - used in xrp-asym, will reverse-engineer
* 'claim' (for BTP, this uses a Transfer call instead of a Message call), 'last_claim' - used in xrp-asym, will reverse-engineer
* 'info' (new version, different from the 17Q4 one)

The 'balance' protocol is no longer part of this list, because it was moved up into IL-DCP

**Comment by dappelt** [comment]
Also, if it is relevant for your list, `ilp-plugin-xrp-paychan` uses the protocol `ripple_channel_id`.

**Comment by adrianhopebailie** [comment]
@michielbdejong I still think it would be valuable to document these and possibly in away that they can be generalized and re-used for other settlement ledgers that use payment channels (if possible):

 - 'channel', 'fund_channel', 'channel_signature' - used in xrp-asym, will reverse-engineer
 - 'claim' (for BTP, this uses a Transfer call instead of a Message call), 'last_claim' - used in xrp-asym, 
 - will reverse-engineer
 - 'info' (new version, different from the 17Q4 one)

**Comment by karzak** [comment]
I'm planning on documenting the various sub protocols that are currently being used in plugins. I'm not quite sure how to format it, so please take a look at this example at let me know what you were thinking. 

Can't upload markdown on github, so you can convert it to .md for pretty formatting. 


[0031-btp-sub-protcols.txt](https://github.com/interledger/rfcs/files/2185952/0031-btp-sub-protcols.txt)
