### ISSUE TITLE
All-Address Regex in RFC-15 allows Invalid Destination Addresses

### ISSUE THREAD

**Issue by sappenin** [interledger/rfcs#386]
The **All Addresses** REGEX in [RFC-15](https://github.com/interledger/rfcs/blob/master/0015-ilp-addresses/0015-ilp-addresses.md#address-requirements) has a minor bug, where it allows an address like `g.bob`, which violates requirement 5 of the `Address Requirements`, which says:

> Destination addresses ... MUST contain at least two segments after the allocation scheme prefix.

I initially thought simply changing the `*` to a `?` just before the 3rd capturing group would fix the Regex, but doing that disallows the `g.`, and other top-level prefix-addresses.

Here's an example with some test vectors: https://regex101.com/r/BFqOk6/3/tests

**Comment by pascalav** [comment]
What about `(?=^.{1,1023}$)^(g|private|example|peer|self|test[1-3]?)[.](?:([a-zA-Z0-9_~-]+[.])*|([a-zA-Z0-9_~-]+[.])+[a-zA-Z0-9_~-]+)$` ?

It uses a non-capturing group for the address prefix vs. destination address division part.

Tested successfully at https://regex101.com/r/mLu4RR/1/tests
