### ISSUE TITLE
Fix errors related to amounts, balances, and bandwidth

### ISSUE THREAD

**Issue by emschwartz** [interledger/rfcs#397]
We need to decide on the error codes that will be returned when a packet exceeds the balance or bandwidth so that the sender can react appropriately.

**Currently Implemented in the Connector**
- [Balance limit exceeded in connector middleware](https://github.com/interledgerjs/ilp-connector/blob/master/src/middlewares/balance.ts#L34): `F00: Bad Request`
- [Maximum packet amount exceeded](https://github.com/interledgerjs/ilp-connector/blob/master/src/errors/max-packet-amount-exceeded-error.ts): `F03: Invalid Amount`
- [Throughput exceeded](https://github.com/interledgerjs/ilp-connector/blob/master/src/errors/throughput-exceeded-error.ts): `F02: Unreachable`
- [Rate limit exceeded](https://github.com/interledgerjs/ilp-connector/blob/master/src/errors/rate-limit-exceeded-error.ts): `F02: Unreachable`

(The plugins are even worse because they don't return any ILP Reject packets at all: https://github.com/interledgerjs/ilp-plugin-xrp-asym-server/issues/20, https://github.com/interledgerjs/ilp-plugin-mini-accounts/issues/22)

**Proposal**
- Balance limit exceeded: `T04: Insufficient Liquidity` or a new error
- Max packet amount: new final error `F08: Maximum Payment Size Exceeded` (the amount isn't really _invalid_, it's just too high for this path)
- Throughput exceeded: `T05: Rate Limited` or a new error if we want to differentiate between "you're sending too many packets and you're sending too much money"
- Rate limit exceeded: `T05: Rate Limited` (just needs to use the right code)

**Comment by justmoon** [comment]
Nice, thanks for working on this!

> Balance limit exceeded: T04: Insufficient Liquidity or a new error

Yeah, T04 sounds right.

> Max packet amount: new final error F08: Maximum Payment Size Exceeded (the amount isn't really invalid, it's just too high for this path)

:+1:

> Throughput exceeded: T05: Rate Limited or a new error if we want to differentiate between "you're sending too many packets and you're sending too much money"

I would have expected T04 here. A throughput limit is more like a liquidity limit to me than a rate limit imo. Throughput and balance limits prevent me from spending too much money. A rate limit prevents me from overloading the connector's CPU/memory/bandwidth.

If anyone disagrees strongly with this I would say another option would be to just create a separate T** code for throughput exceeded.

> Rate limit exceeded: T05: Rate Limited (just needs to use the right code)

Yes, T05 is right.

**Comment by adrianhopebailie** [comment]
> Max packet amount: new final error F08: Maximum Payment Size Exceeded (the amount isn't really invalid, it's just too high for this path)

Is there a good reason to differentiate this from F04?

**Comment by emschwartz** [comment]
`F04: Insufficient Destination Amount` sounds like it's saying "you sent too little", whereas `F08: Maximum Payment Size Exceeded` is "you sent too much".

**Comment by adrianhopebailie** [comment]
> Insufficient Liquidity is T04 

Ah! Sorry, confusing my F's and T's.

So are we saying exceeding maximum payment size is a permanent error? i.e. F08 as opposed to T04

**Comment by emschwartz** [comment]
I think all of the issues here have been resolved
