### ISSUE TITLE
RFC - 15 - peer.config is an invalid address

### ISSUE THREAD

**Issue by adrianhopebailie** [interledger/rfcs#410]
According to the ILP Address spec the address `peer.config` is invalid.

> Destination addresses MUST NOT end in a period (.) character, and MUST contain at least two segments after the allocation scheme prefix.

Since this address is used in protocols such as ILDCP it's clear that not all implementations are strictly following the ILP Address specification.

The specification should be updated or ILDCP should use a valid address.

This was uncovered in the Quilt implementation when the ILP Address parsing libs were upgraded to strictly follow the rules in the spec. See https://github.com/hyperledger/quilt/issues/128

**Comment by emschwartz** [comment]
I think `peer` should be added as a prefix and we should get rid of the number of segment requirement

**Comment by sappenin** [comment]
It feels weird to get rid of the number-segment rule in RFC-15 because shouldn't there _always_ be a  thing called a "ledger" in any ILP address? For example: 

Ledger:`peer.davidadrian.`
Ledger Account: `peer.davidadrian.david`

This is _slightly_ weird in the `peer` case because all accounts on the `peer.davidadrian.` ledger will do the same thing....but it seems like we should maintain the rule for the general case.

Otherwise, if we remove the rule, then the global-prefix and the ledger-identifier for something like `peer.config` would be _peer_....is that correct?

**Comment by adrianhopebailie** [comment]
> It feels weird to get rid of the number-segment rule in RFC-15 because shouldn't there always be a thing called a "ledger" in any ILP address?

I think you are right but in the case of `peer`, that address space is limited to only accounts that can exist between the two peers, so the ledger is implicit/virtual.

So, the question is:

* Should we drop the number of segment requirement OR
* Should we make `peer` an exception to that rule?

**Comment by justmoon** [comment]
> It feels weird to get rid of the number-segment rule in RFC-15 because shouldn't there always be a thing called a "ledger" in any ILP address?

No. Connectors are perfectly valid addressable entities. And any top-tier connector will have a two segment address. For instance, feel free to ping `g.zero` on livenet which is my connector.

**Comment by adrianhopebailie** [comment]
> Connectors are perfectly valid addressable entities.

An ILP Address must be addressing an account. If your connector has multiple accounts in different currencies what happens if I send a payment to `g.zero`? How do I know which account was credited and therefor the currency and scale of the amount you received?

**Comment by adrianhopebailie** [comment]
Ping @justmoon @emschwartz 
Would be useful to get consensus on this please, so we can unblock https://github.com/hyperledger/quilt/issues/128

Answering my own question above, an ILP Address addresses both connectors and their accounts. Where a payment is addressed to a connector (like `g.zero`) then the account it is delivered into will depend on which peer delivers the payment.

I propose we modify the spec to say:

> Destination addresses MUST NOT end in a period (.) character, and MUST contain at least **one** segment after the allocation scheme prefix.

**Comment by sappenin** [comment]
+1 to your modification.

**Comment by justmoon** [comment]
:+1: on @adrianhopebailie 's modification.

> Answering my own question above, an ILP Address addresses both connectors and their accounts. Where a payment is addressed to a connector (like g.zero) then the account it is delivered into will depend on which peer delivers the payment.

I'd propose a slightly different conceptualization: I don't think ILP addresses ever address an account.

Interledger is a graph. Nodes (connectors, mini-connectors, clients, senders, receivers, listeners, etc.) are the vertices and accounts are the edges.

ILP addresses are identifiers and locators for ILP **nodes**. A fulfilled ILP packet will modify the balances for all accounts along the path between the sending node and the receiving node. This is no different for a connector than for an SPSP receiver. Both are ILP nodes and in both cases, the accounts whose balances change are all accounts along the path. Sure, there will usually be a 1:1 relationship between a receiver and the receiver's account with its local moneyd but that's different than saying the payment is *addressed* to the account. It is still addressed to the receiver.

Note that balances are not always tracked/recorded. Some accounts are limited only by bandwidth, others are not limited and/or recorded at all.

**Comment by adrianhopebailie** [comment]
> Note that balances are not always tracked/recorded. Some accounts are limited only by bandwidth, others are not limited and/or recorded at all.

@justmoon can you expand on this a little?

> ILP addresses are identifiers and locators for ILP nodes.

True, but the reality is that if a node is peered with multiple others then the account that is impacted by an incoming payment is the account held with the peer that forwards the payment.

E.g. A node is addressed as `g.bob` and is peered with `g.chloe` and settlement occurs in XRP but is also peered with `g.chris` and settlement occurs in BTC. `g.fred` is also peered with both `g.chloe` and `g.chris` and is Alice's ILSP. 

If Alice sends a payment addressed to `g.bob` via `g.fred` she has no idea if it will be delivered via `g.chloe` or `g.chris`, i.e. in XRP or BTC.

Likewise, Bob has no idea if we'll be getting XRP or BTC if he simply gives out the address `g.bob` for payment.

While this doesn't break anything it would make sense for Bob to advertise different addresses to Chris and Chloe (like `g.bob.xrp` and `g.bob.btc`).

So, I would tweak your phrasing slightly to say: addresses are for nodes but nodes may have multiple addresses and will likely use different addresses for different accounts.
