### ISSUE TITLE
ILP URI Scheme?

### ISSUE THREAD

**Issue by adrianhopebailie** [interledger/rfcs#411]
Building on some of the discussion in #409 I propose we register an ILP URI scheme to solve for the use cases described there.

Possible scheme based on the generci syntax in [RFC 3986](https://tools.ietf.org/html/rfc3986): 

```
"ilp:" ilp-address [ "?" query ] [ "#" fragment ]
```

Examples: 

 - `ilp:g.foo.bar`
 - `ilp:peer.config`
 - `ilp:test.amadeus.bob?psk=65rdfetfd65fhgteslKUHUYrtstGFDtyre`

**Comment by sappenin** [comment]
What would be the difference between `Interactions` field defined in RFC-15 (i.e., the stuff after the`~` character  in the ILP Address) and the `query` and `fragment` fields in an `ilp:` URI?

**Comment by michielbdejong** [comment]
The `ilp:test.amadeus.bob?psk=65rdfetfd65fhgteslKUHUYrtstGFDtyre` format looks useful! It covers the first two fields from https://github.com/interledger/rfcs/blob/master/0009-simple-payment-setup-protocol/0009-simple-payment-setup-protocol.md#response 
Can all the other fields present in there be considered optional, or discovered in other ways?

**Comment by adrianhopebailie** [comment]
> What would be the difference between Interactions field defined in RFC-15 (i.e., the stuff after the~ character in the ILP Address) and the query and fragment fields in an ilp: URI?

They have different target consumers. The data in the query and fragment is used by the consumer of the URI and may never be sent in the payment itself whereas the data in the `Interactions` filed is consumed by the receiver.

**Comment by adrianhopebailie** [comment]
> Can all the other fields present in there be considered optional, or discovered in other ways?

Some use cases don't require all of those fields. Where they are required I'd imagine they would be passed as query string params.

**Comment by adrianhopebailie** [comment]
Also note the proposal for a `payto:` scheme at IETF: https://mailarchive.ietf.org/arch/msg/uri-review/D_IeQiXnWzT53dCPCh13zXR6LC4/?qid=576708d4d0747a201e1e936787a4a927
