### ISSUE TITLE
Document ILDCP

### ISSUE THREAD

**Issue by adrianhopebailie** [interledger/rfcs#431]
Document ILDCP and any other uses of the `peer.config` as implemented in [interledgerjs/ilp-protocol-ildcp](https://github.com/interledgerjs/ilp-protocol-ildcp)

**Comment by dora-gt** [comment]
I started to write this. If anyone else is also trying to do this, please tell me to avoid writing the same document.

**Comment by dora-gt** [comment]
@adrianhopebailie We can probably close this issue, since #446 is closed.

**Comment by adrianhopebailie** [comment]
Fixed in 04ddfef
