### ISSUE TITLE
Explicit LICENSE notice for this interledger/rfcs

### ISSUE THREAD

**Issue by tnir** [interledger/rfcs#473]
Explicit LICENSE notice for this repo is preferred while [package.json](https://github.com/interledger/rfcs/blob/05ab457b9301b031e1ec954632582a325c4907b4/package.json) is stating about [ISC](https://opensource.org/licenses/ISC).

**Comment by tnir** [comment]
@emschwartz I'd like to know license of this repo. Any idea?

**Comment by adrianhopebailie** [comment]
@tnir - the community operates under the auspices of a W3C Community Group therefor all output is governed by that process: https://www.w3.org/community/about/agreements/summary/

That said, the IL-RFCs should have an explicit copyright license and we have discussed this in the past but not made a final decision.

I think we SHOULD use the CC-BY-SA license but I'd also not be against a simple CC-0 license.

@emschwartz @justmoon @sharafian @michielbdejong @mDuo13 WDYT?

**Comment by mDuo13** [comment]
I'm in favor of using CC-BY-SA.

**Comment by sappenin** [comment]
If we use [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/), what do we need to do in these repos? Put the badge in each RFC? And in the project's README?

**Comment by tnir** [comment]
Thanks all. My original point was (at least) to put [this license file](https://creativecommons.org/licenses/by-sa/4.0/legalcode.txt) as `LICENSE` (or `LICENSE.txt`) under the root of this repo in order to get users informed.

See also https://choosealicense.com/licenses/cc-by-sa-4.0/

**Comment by tnir** [comment]
Thanks for addressing this 🙇
