### ISSUE TITLE
RFC-4: Remove cancellation condition

### ISSUE THREAD

**Issue by justmoon** [interledger/rfcs#48]
Atomic mode will likely be used only between tightly-knit subgroups. We can simplify the general ILP implementation by removing cancellation conditions from the ledger plugin API.

This ticket is a strawman to see if anyone can come up with a compelling reason why we would want to keep cancellation conditions around.

Reasons to remove:

* Simpler ledger plugins
* Harder for connectors to shoot themselves in the foot

See also: #28

**Comment by emschwartz** [comment]
👍 👍

**Comment by emschwartz** [comment]
Closed by https://github.com/interledger/rfcs/commit/2afa9b9c979ed998c7ce0c066dae0990fe2cde22
