### ISSUE TITLE
Update IL-RFC-30 discussion of timestamps and GeneralizedTime wrt ILP and BTP

### ISSUE THREAD

**Issue by sappenin** [interledger/rfcs#480]
This [ASN.1 definition for BTP](https://github.com/interledger/rfcs/blob/master/asn1/BilateralTransferProtocol.asn#L58) specifies `GeneralizedTime` as the type for `Error.triggeredAt` and `Prepare.expiresAt`.

However, per [this comment](https://github.com/interledger/rfcs/issues/440#issuecomment-405197100) from @adrianhopebailie, no ASN.1 definitions should reference `GeneralizedTime`, but should instead use `InterledgerTimestamps` (see [spec here](https://github.com/interledger/rfcs/blob/master/0030-notes-on-oer-encoding/0030-notes-on-oer-encoding.md#timestamp)).

**Comment by emschwartz** [comment]
Actually BTP does use Generalized Time rather than Interledger timestamps: https://github.com/interledgerjs/btp-packet/blob/master/index.js#L26-L27

**Comment by sappenin** [comment]
Ah, yes, you're right.

So, it seems like Interledger packets use [Interledger timestamps](https://github.com/interledgerjs/ilp-packet/blob/master/index.ts#L3) but BTP is using the special variant of GeneralizedTime (per you [link](https://github.com/interledgerjs/btp-packet/blob/master/index.js#L26-L27) above).

So, I suppose [IL-RFC-30](https://github.com/interledgerjs/btp-packet/blob/master/index.js#L26-L27) is incorrect, then? Those rules only apply to BTP, but not to ILP packets?

**Comment by adrianhopebailie** [comment]
> So, I suppose IL-RFC-30 is incorrect, then?

Yes. It needs to be updated.

> However, per this comment from @adrianhopebailie, no ASN.1 definitions should reference GeneralizedTime, but should instead use InterledgerTimestamps

Sorry, I meant for ILP. The rationale for the switch was fixed size which is probably less relevant for BTP

**Comment by sappenin** [comment]
Makes sense - so I think the ASN definition is correct, but IL-RFC-30 needs to be cleaned up. Should I create a separate ticket and close this one?

**Comment by adrianhopebailie** [comment]
Let's just track it here for context.

**Comment by sappenin** [comment]
Bumping to keep this open a bit longer...
