### ISSUE TITLE
Proposal: clean up deprecated repos in Interledger.js

### ISSUE THREAD

**Issue by kincaidoneil** [interledger/rfcs#487]
In light passing the 100 (!) repo milestone in Interledger.js, I think it's time for some house cleaning. The sheer number of repos, many of which are named similarly or duplicate functionality, is fatiguing, and necessitates discovering "what is deprecated?" part of the process of developing on Interledger. We should fix that.

#### I propose, for all the following repos, either moving them to the [Interledger deprecated](https://github.com/interledger-deprecated) organization, or archiving them (making them read-only and clear they're not used):

Recent, plugin-related, unnecessary:
- [x] **ilp-plugin-ethereum-asym-client** -- server and client are both wrapped into ilp-plugin-ethereum
- [x] **ilp-plugin-lnd-asym-client** -- server and client are both wrapped into ilp-plugin-lightning
- [x] **lnd-lib** -- no longer used in the Lightning plugin
- [x] **moneyd-eth** -- not to be confused with moneyd-uplink-eth, this was a port from xrp that was never finished and has been superseded by the uplink-eth
- [x] **ilp-plugin-mini-balances** -- experiment by Ben that I believe is superseded by ilp-plugin-payment

Defunct testnet (replaced with a new testnet bootstrapped by Strata & Kava):
- [x] **interfaucet**
- [x] **amundsen**

Connector shard related/dependents (will this be used in the future?):
- [x] **ilp-connector-shard**
- [x] **ilp-connector-route-manager**
- [ ] **ilp-routing**
- [x] **ilp-schemas** -- no dependent repos; unclear if it's important

Loopback transport (not an official spec/actively developed):
- [x] **ilp-protocol-lp**
- [x] **ilp-protocol-lsd**

Very old repos from previous protocol versions:
- [x] **ilp-kit**
- [x] **five-bells-ledger**
- [x] **ilp-plugin-bells**
- [x] **five-bells-shared**
- [x] **ilp-kit-docker-compose**
- [ ] **five-bells-condition**
- [x] **ilp-plugin-payment-channel-framework**
- [x] **ilp-plugin-chain** -- LPI v1
- [x] **btp-toolbox** -- BTP v1
- [x] **ripple-cli** -- fork, very old
- [x] **spsp** -- spsp client that was never developed
- [x] **ilp-plugin-paypal** -- LPI v1
- [x] **ilp-plugin-human** -- LPI v1
- [x] **ilp-settlement-example**
- [x] **five-bells-demo**
- [x] **ilp-packet-viewer** -- the first of many CLI tools to view ILP packets
- [ ] **ilp-connector-backend-yahoo**
- [x] **ilp-plugin-tests**
- [x] **ilp-kit-cli**
- [x] **ilp-plugin-shared**
- [x] **ilp-demo-maker**
- [x] **ilp-plugin-settlement-adapter**
- [x] **ilp-plugin-virtual**
- [x] **ilp-plugin-integration**
- [x] **five-bells-notary**
- [x] **five-bells-visualization**
- [x] **ilp-core**
- [x] **ilp-lightning-demo** -- outdated, superseded by newer Lightning plugin

If any of these should not be deprecated, please comment and I'll remove them from the list. On the flip side, if there's anything missing from the list, let's clean that up too!

**Comment by emschwartz** [comment]
@justmoon Can you make me an owner and @kincaidoneil a contributor of the interledger-deprecated org? I can move repos over right now but can't add other people so that they'd be able to move them too

**Comment by sappenin** [comment]
These repos can also be moved (I don't have permission in [interledger-deprecated](https://github.com/interledger-deprecated) either, so I can't do it myself):

- [ ] java-ilp-core
- [ ] java-ilp-client
- [ ] java-ilp-connector
- [ ] java-ilp-plugin
- [ ] java-ilp-client-spring-boot
- [ ] java-ilp-ledger-adaptor-rest-spring
- [ ] java-ilp-ledger-simple

**Comment by emschwartz** [comment]
All of the above (save for those still used or kind of used) moved to interledger-deprecated

**Comment by justmoon** [comment]
@emschwartz Made you an owner and invited @kincaidoneil!
