### ISSUE TITLE
Change description of F04 error?

### ISSUE THREAD

**Issue by kincaidoneil** [interledger/rfcs#537]
In the ILPv4 spec, the description of an F04, "Insufficient Destination Amount" error is:

> The receiver deemed the amount insufficient, for example you tried to pay a $100 invoice with $10.

But this example doesn't make sense, since it's discouraged to pay an entire invoice with a single packet.

I propose a slight tweak to the description that I think might make the error more useful:

> The receiver deemed the amount insufficient, for example, the effective exchange rate was too low.

Thoughts?

**Comment by adrianhopebailie** [comment]
cc @emschwartz @justmoon

**Comment by emschwartz** [comment]
Works for me

**Comment by sappenin** [comment]
@kincaidoneil does #541 do what you were thinking?
