### ISSUE TITLE
0028: dynamic meta tags security issues

### ISSUE THREAD

**Issue by sublimator** [interledger/rfcs#540]
@adrianhopebailie foresees some security issues with the way we are monitoring for dynamically injected meta tags.

**Comment by traviscrist** [comment]
Are there more details to this that can be captured in this issue so others know what the security issues are?

**Comment by adrianhopebailie** [comment]
I have a suspicion that we are not immune from another extension modifying the Payment Pointers on a site before we process the tags.

This is an issue to track this discussion but @sublimator and I agreed we need some expert opinion from browsers on how to do SPA's safely

**Comment by sublimator** [comment]
Essentially any 3rd party code, so currently the model is, 'beware of what scripts you pull in' as an integrator and 'be careful what extensions you install' as an end user. The store review/rating process can help with the latter, but of course ...

**Comment by sublimator** [comment]
Another point worth capturing here is that even before the observation of meta tags change, there was  **seemingly** no real way of knowing from a polyfill (extension or script injected) whether the tags were from an SSL served static html document.

**Comment by sublimator** [comment]
Beyond of course, re-requesting the document, with all the complications
that would involve.

**Comment by sublimator** [comment]
And of course, it shares these issues with previous imperative `donate(...)` and `monetize(...)` apis.
