### ISSUE TITLE
STREAM RFC: codify the conditions for a ConnectionAssetDetails frame being returned from a receiver.

### ISSUE THREAD

**Issue by theotherian** [interledger/rfcs#546]
**Information that inspired this issue:**

- https://github.com/interledgerjs/ilp-protocol-stream/pull/69
- Discussion on https://github.com/interledger-rs/interledger-rs/issues/273
- Discussion on https://github.com/hyperledger/quilt/issues/261

Proposal:
STREAM RFC (il-rfc29) should codify the conditions for a `ConnectionAssetDetails` frame being returned from a receiver.

Question: What is the correct way to indicate a new Connection for a receiver?
Option1: Treat sequence of 1 as a new connection.
Option2: Whenever a ConnectionNewAddressFrame and a SendMoneyFrame are encountered.
Option3: Leave the RFC as is, which suggests only stateful receivers (see next question).

Question: should there be stateless receivers, or is this a protocol violation?

Question: What should a receiver reply with on a new connection?
Stateless:
- When receiver receives a `ConnectionNewAddress` and a `StreamMoneyFrame` frame from a sender, it should reply with a `ConnectionAssetDetails` frame.

Stateful:
- When receiver receives its first `StreamMoneyFrame` for a given connection, it should reply with a `ConnectionAssetDetails` frame.

**Comment by adrianhopebailie** [comment]
@sappenin and @kincaidoneil https://github.com/interledgerjs/ilp-protocol-stream/issues/112 was never resolved, does it have any bearing on this?

**Comment by kincaidoneil** [comment]
> was never resolved, does it have any bearing on this?

Not really, I think it just underscores that it's important for the sender and recipient to exchange asset details, so we should support that for stateless receivers. AFAIK, David's PR should be fully compatible with the existing JS Stream implementation.
