### ISSUE TITLE
Tracking: RFC Breaking Changes for STREAM V2

### ISSUE THREAD

**Issue by sappenin** [interledger/rfcs#554]
This ticket is meant to track various proposals related to a potential STREAM V2. The reason we're not making breaking changes in STREAM v1 is that there are already implementations in the wild that use V1, and we don't want to break them or force people to update software.

So, let's use this ticket to catalog any improvements to STREAM that we might want to include in the next version.

* Fix Encryption AuthTag Ordering (https://github.com/interledger-rs/interledger-rs/issues/310)
* Use a standard HKDF (consider [RFC-5869](https://tools.ietf.org/html/rfc5869) and see [here](https://eprint.iacr.org/2010/264.pdf) for more details). Note that transitioning to a standards-based KDF doesn't add any security value unless we start exchanging a `salt` during SPSP, and this would only provide marginal value due to the way we use STREAM. So, primary benefit here is just using a standard KDF. Quilt example PR here. 
* Add ability to request `ConnectionAssetDetails` without sending a `ConnectionNewAddressFrame` (see https://github.com/interledger/rfcs/issues/571) and https://github.com/hyperledger/quilt/issues/445.

**Other references**
* https://github.com/interledger/rfcs/pull/551
* https://github.com/interledger/rfcs/issues/546
* [Clarify STREAM Connection Details Functionality](https://github.com/interledger/rfcs/pull/573)

**Comment by kincaidoneil** [comment]
> Decide what the best way to exchange Connection Asset details is (SPSP or some higher layer, ConnectionAssetDetails frame, some new frame?). See #551 as well as #546.

Can't we resolve this now without a breaking change? Alternatively, if this should be at a higher layer, could we also address this now in a backwards-compatible way?

**Comment by sappenin** [comment]
> Can't we resolve this now without a breaking change

Possibly, but not in this ticket. This is just a tracking ticket for the day, perhaps very far into the future, that we decide to work on STREAM v2. For now, this is basically where we can track things that _probably should_ be fixed, but for which we lack enough knowledge to make a good decision....or, for which the cost of fixing existing implementations is large enough that we don't want to make breaking changes in a one-off manner (i.e., we want to make only a single set of breaking changes, once we've collected enough of them to justify prodding everyone to upgrade).

**Comment by sappenin** [comment]
Bump
