### ISSUE TITLE
Define normalization algorithm for header data to be used in conditions

### ISSUE THREAD

**Issue by adrianhopebailie** [interledger/rfcs#56]
From: https://github.com/interledger/rfcs/issues/54#issuecomment-232892378

To use header data in the condition it must be normalized before it is signed/hashed. The algorithm for this needs to be standardized so it is repeatable and deterministic.

**Comment by emschwartz** [comment]
To be more precise, the ASN.1 `SEQUENCE` types already define the ordering of the fields within a given header. I think what you're saying is that we should have a recommended ordering for the different headers attached to a packet (see [IPv6](https://tools.ietf.org/html/rfc2460#section-4.1))

**Comment by adrianhopebailie** [comment]
Yes. If the data that is being signed includes multiple headers (ILP + ITP for example) then we need to define how to normalize the combined data
