### ISSUE TITLE
Remove legacy ASN.1 definitions

### ISSUE THREAD

**Issue by kincaidoneil** [interledger/rfcs#569]
I noticed the link in the Interledger v4 RFC links to an "InterledgerPacket" ASN.1 file, which defines older types of packets. I think these files should be removed for clarity:

- `asn1/InterledgerPacket.asn`
- `asn1/InterledgerPaymentRequest.asn`
- `asn1/InterledgerQuotingProtocol.asn`
- `asn1/LegacyInterledgerProtocol.asn`
- `asn1/PreSharedKeyV2.asn`

Can these be safely deleted (and there'll still be in the commit history for future reference)?

**Comment by sappenin** [comment]
I think everything in that list can be deleted except [InterledgerPacket.asn](https://github.com/interledger/rfcs/blob/master/asn1/InterledgerPacket.asn#L49). That still defines the current ILPv4 packet types (12, 13, and 14).

I think we could probably get rid of this [Liquidity Curve](https://github.com/interledger/rfcs/blob/master/asn1/InterledgerTypes.asn#L74) section, though.

**Comment by sappenin** [comment]
@kincaidoneil are you going to make the changes suggested above, or should we close this one?

**Comment by sappenin** [comment]
@kincaidoneil are you going to make the changes suggested above, or should we close this one?

**Comment by kincaidoneil** [comment]
@sappenin At last... [here's that PR](https://github.com/interledger/rfcs/pull/579)!
