### ISSUE TITLE
RFC-4 - Allow RejectTransfer for any incoming transfer

### ISSUE THREAD

**Issue by adrianhopebailie** [interledger/rfcs#64]
The protocol currently allows for a transfer to be sent with no condition therefor it must define what a connector must do if it receives such a transfer and wants to reject it.

Right now the interface defines a `rejectTransfer` method for this but limits this to only transfers that are pending.

If a connector is able to use the same method to reject a transfer without a condition then this can be defined as the desired behaviour in the protocol.

**Comment by emschwartz** [comment]
Right now, transfers that have no execution condition are executed immediately by the ledger.

In order to support this feature, I believe we would need:
- ledgers to emit a specific event when there is an incoming transfer being held pending authorization (separate from the notification that there are funds on hold pending a condition fulfillment so the recipient knows how to respond)
- ledgers to wait for positive acknowledgement from connectors or receivers before executing transfers even if they do not have conditions
- the plugin interface would need an `acceptIncomingTransfer` method
- transfers would need expiries even if they don't have conditions, because you wouldn't want money to be held forever waiting for the recipient to accept it

I think we would also need to decide whether this is the default behavior, such that connectors and receivers should be built to _always_ provide positive authorization for incoming funds, or whether it is a feature they need to check if a ledger supports.

This seems like it might be quite a complicated feature to add to the integrations for cryptocurrencies.

**Comment by adrianhopebailie** [comment]
I don't think it's only possible for a connector to reject an incoming transfer **before** it happens. That's why I don't think the "authorized credits" feature is the only use case for this.

What if a ledger processes a direct transfer and notifies the receiving connector. The connector looks at the associated ILP data and attempts to route the transfer but it can't. It needs to tell the ledger to transfer the funds back to the original sender.

This can't be treated like a new local transfer because there is the possibility of incurring fees etc. It is actually just a reversal of the original local transfer.

From a design perspective, we should think of methods and events as being completely decoupled so we can be fully asynchronous in our implementations. Put differently, I think it's a mistake to try and enforce the protocol rules through the programming interface.

The contract defined by the interface (API) should make no claims about what events will be emitted when specific methods are called. Instead the API must define events in such a way that when an event consumer handles an event it is able to interpret what it must do from the event data and it's knowledge of the protocol.

That contract of which events the ledger/plugin must emit and when, and which methods should be called by the connectors and when (the orchestration) is defined by the protocol. i.e. Implementors implement the interface but still need to read the protocol spec to make sure they are building a conforming implementation.

For a direct transfer that is rejected by the receiver the following sequence of method calls and events is probably logical:
1. Sender -> Ledger.sendTransfer()
2. Ledger -(outgoing transfer event)-> Sender
3. Ledger -(incoming transfer event)-> Receiver
4. Receiver -> Ledger.rejectTransfer()
5. Ledger -(incoming reject event)-> Receiver
6. Ledger -(outgoing reject event)-> Sender

However if the ledger rejects the transfer (because optimistic payments have been turned off - a feature of the implementation) then the flow should be:
1. Sender -> Ledger.sendTransfer()
2. Ledger -(incoming reject event)-> Receiver
3. Ledger -(outgoing reject event)-> Sender

This allows implementations to be very modular (the event processor doesn't even need to share state with the component that calls the methods).

All of this said, we should consider the implications of events being consumed and acted on asynchronously and if that may cause problems. i.e. What if a receiver rejects a transfer before the sender has even processed the event that notifies them the transfer was sent? Is it enough for the ledger to simply enforce ordering of events per consumer?

**Comment by emschwartz** [comment]
I think you're making reasonable arguments for these features, but I think the one you just mentioned is yet another feature. Rejecting funds before and after they are received are different features: authorized credits and reversals.

Re: authorized credits. My point about needing to add those functions and events to the plugin is that if there is a way to reject a transfer and authorization is required, you need a way to find out that you're supposed to provide that authorization and a function for actually doing so.

Re: reversals. If there is a way to "reject" a transfer _after_ it has been received, that adds quite a bit of complexity to dealing with transfers. How do you know when money has been _sent_? If it can always be "rejected" (i.e. reversed), is it ever actually "final"? I do not think we should add reversals as you describe them to ILP. Higher level schemes should be perfectly capable of linking multiple transfers together. I would argue that the core ILP should concern itself with unidirectional transfers, not reversals after funds have been received.


In general, I think the points you're bringing up about connectors being unable to route payments and wanting to send them back is a strong argument for using conditions. Optimistic mode should only be used when the amount of money is so small that it would be fine behavior for the connector to just keep the money if there's a problem.

**Comment by adrianhopebailie** [comment]
> I think you're making reasonable arguments for these features, but I think the one you just mentioned is yet another feature.

I am not talking about implementation features. I'm explicitly saying that we must define the interface without thinking about the implementation complexity or how this would be exposed by the implementation as a new feature.

At a protocol level we MUST define all behaviour of the actors for all cases. Right now we have a hole in our protocol specification around dealing with unroutable or unwanted optimistic payments.

It's fine for an implementation to not care about this and simply not allow a connector to reject an incoming optimistic transfer but it should do this by throwing an exception when the connector calls rejectTransfer and specifying in it's own documentation that it will never emit an outgoing reject event for an optimistic transfer.

**Comment by justmoon** [comment]
For cases where receiving money unintentionally is a concern, the receiver should set a flag that disallows incoming optimistic transfers and the ledger should only allow the receiver to fulfill conditions. (credit to @bensharaf)

For cases where it's not that much of a concern, the receiver should simply send the money back.

> This can't be treated like a new local transfer because there is the possibility of incurring fees etc.

There could be a special "refund" message you can put as a memo, which references the original transfer. The ledger checks to make sure that the refund is for an existing, not-yet-refunded transfer in the opposite direction and if so, charges no fee for it.

Personally I think that's quite overkill, but if a ledger feels the need they'd be able to implement that.

**Comment by adrianhopebailie** [comment]
I think we're all missing each other a bit here, perhaps because this issue is logged against the ledger plugin which is an implementation or perhaps I am just missing something.

I am looking at this interface through the lens of defining something that is implementation agnostic. Because it is our only reference implementation and is therefor an _implicit protocol definition_.

In defining the way a connector and a ledger interface with one another according to ILP (irrespective of what stack this is implemented on) I think we should define the expected behavior of a connector that receives a transfer they don't want (for whatever reason).

If we have another way of defining this, and can simply say that this implementation explicitly doesn't allow for it, then that's fine but I'm not sure what that other way is.

**Comment by emschwartz** [comment]
Unconditional transfers are no longer supported
