### ISSUE TITLE
RFC-9: Questions about design + purpose of SPSP

### ISSUE THREAD

**Issue by emschwartz** [interledger/rfcs#65]
I am looking over SPSP and have a number of questions about its design and purpose.

It seems like many of the options it was originally intended to bundle have since ceased to be options and are now fixed in other layers (e.g. sending "Universal" mode payments is now just sending ILP payments, and much of the request/response payment flow has been implemented in [ITP](https://github.com/interledger/rfcs/blob/master/0011-interactive-transport-protocol/0011-interactive-transport-protocol.md)).

As far as I can tell, this is what SPSP provides:

## SPSP Features
- Optional email-style identifiers for human readability
- Handling end-to-end communication (which is explicitly left out of ITP) using HTTP
- Standard API for peer-to-peer and invoice payments, two common use cases

## Use Cases

Steps that are actually SPSP (versus a lower level protocol) are in **bold** (it's not that much)

### Sending Peer-to-peer Payment, Fixed Destination Amount
**0. (Optional) Discover - resolve human-readable identifier into URL**
**1. Setup - post payment params (amount, maybe sender id), get ILP Packet**
2. Quote - check how much it would cost to delivery the packet
3. Execute

### Paying Invoice
**0. (Optional) Discover - resolve human-readable identifier into URL**
**1. Setup - get ILP Packet (no params)**
2. Quote - check how much it would cost to delivery the packet
3. Execute

### Sending Peer-to-peer Payment, Fixed Source Amount
**0. (Optional) Discover - resolve human-readable identifier into URL**
**1. Query - get ILP address from receiver endpoint**
2. Quote - find out how much receiver will receive
**3. Setup - post payment params, get packet**
4. Execute (create transfer based on original source amount, NOT based on packet)

## Questions

- Does the fixed destination amount use case make sense to include? How would the sender know how many units it would want the destination to receive if it doesn’t even know what ledger the destination is on?
- If the only reason we need the Query step is to return the ILP address for fixed source amount payments so you can quote a payment to it, can we combine that endpoint with the Setup one? (https://github.com/interledger/rfcs/issues/49 proposes combining Query and Quote, but Query goes to the receiver endpoint, whereas Quote goes through core ILP/ILQP to the connector)
- Should the receiver endpoint return a binary packet or a JSON form that the client then turns into the packet to send? If it’s binary the receiver can include opaque routing headers that the sender won’t need to understand, but then we have a base64-encoded blob in an HTTP protocol. If it’s JSON then the SPSP client needs to reliably turn the JSON into the binary packet to send, and then the receiver needs to extract the same info from the packet to be able to regenerate the condition fulfillment.
- Should the execution condition be based on the binary packet or an SPSP-specific representation of the fields to check? (Does it matter if SPSP uses [ITP](https://github.com/interledger/rfcs/blob/master/0011-interactive-transport-protocol/0011-interactive-transport-protocol.md)?)
- If SPSP only needs one endpoint and that endpoint might even return a binary packet, should this be a protocol over HTTP? (Note it would probably be worth exploring combining ITP with IPFS’ [libp2p](https://github.com/libp2p/js-libp2p) for a transport-independent p2p application-layer protocol)
- Could a receiver endpoint return different ILP addresses depending on params?

With @bensharaf

**Comment by emschwartz** [comment]
cc @justmoon @adrianhopebailie @vhpoet

**Comment by justmoon** [comment]
The original driver for SPSP was to provide a protocol for payments where the sender is a human using some sort of GUI. Think: The functionality that PayPal provides, but across providers.

## Use cases 

### Peer-to-peer
* As a payer, I want to know the receiver's currency (e.g. USD, EUR etc.) or asset type (e.g. "AAPL shares")
* As a payer, I want destination amounts to be displayed with the correct symbol (e.g. 10 **$** or 100 **shares**)
* As a payer, I want to have a good idea whether a payment will succeed before committing to it (i.e. putting money on hold)

### Merchant/retail
* As a customer, I want to pay invoices exactly once
* As a customer, I want to be able to see the status of an invoice from my wallet history and get more information about the associated order.

### Recurring/subscriptions
* As a customer, I want to be able to see the status of subscriptions, the next payment due and be able to cancel them.

### All types
* As a payer, I want to know that I'm paying the right person (name, logo, etc.)

ITP might be used machine-to-machine, so we don't exchange things like the destination 

Taking a stab at some of those questions:

> Does the fixed destination amount use case make sense to include? How would the sender know how many units it would want the destination to receive if it doesn’t even know what ledger the destination is on?

SPSP tells you the receiver's currency. So for instance, if I'm trying to send you (@emschwartz) money, it might tell me that your currency is euros, so I might decide to send you 4.60 euros for that delicious carrot cake at Konrad's. :)

> If the only reason we need the Query step is to return the ILP address for fixed source amount payments so you can quote a payment to it, can we combine that endpoint with the Setup one?

I was thinking that we might make querying optional. The ability to get information without committing to a payment is an important part of SPSP. For instance, a sender may want to know if they have the right address before they make a payment. So they query and receive a name and avatar that assures them that the address is in fact the right one.

> Should the receiver endpoint return a binary packet or a JSON form that the client then turns into the packet to send?

Binary

> If it’s binary the receiver can include opaque routing headers that the sender won’t need to understand, but then we have a base64-encoded blob in an HTTP protocol.

?

Sending binary over HTTP is totally fine, there is no need for base64 encoding. Every image, file etc that you download over HTTP is binary, it'd be pretty insane if all that would have to be base64 encoded.

> Should the execution condition be based on the binary packet or an SPSP-specific representation of the fields to check?

The packet, as per the ITP spec.

> If SPSP only needs one endpoint and that endpoint might even return a binary packet, should this be a protocol over HTTP?

HTTP is a major reason why SPSP is so simple. Since SPSP is an application layer protocol, it needs to deal with discovery, authentication etc. all of which are things that have solutions in the HTTP/web ecosystem. (Webfinger, TLS, ...)

I think having a p2p application layer protocol would be nice, but it would have rather different tradeoffs compared to SPSP, so I think it would make sense to pursue that separately.

SPSP should require HTTPS for security as well as to avoid any issues with firewalls and such.

> Could a receiver endpoint return different ILP addresses depending on params?

Absolutely!

**Comment by emschwartz** [comment]
Got it, thanks @justmoon

**Comment by adrianhopebailie** [comment]
@emschwartz, I was writing this up when you closed the issue so will just post it but some of these thoughts are perhaps new ideas that I'll log as new issues

The way I think about all of the protocols defined on top of ILP is that their purpose is to give the sender all of the information required to send off that first transfer.

That means:
1. The ILP header (address, destination amount, condition, timeout)
2. The cost to send (local amount)
3. Any additional data that it useful to the sender (receiver name or picture for verification)

Ideally, the protocols for getting each of these would be loosely coupled so they can mixed and matched for different use cases.

Most importantly they mustn't require anyone but the sender and receiver to understand any data they add to the transfer beyond what's in the ILP header.

Sometimes the way one protocol works means it has some restrictions on how well it plays with others. As an example, ITP requires that the condition is defined by the receiver but also that the ILP header is part of that condition so it follows that ITP couldn't be used if the receiving amount wasn't yet known.

I think SPSP is great for a specific set of use cases. That said, I'd like to decouple the WebFinger portion and simply make SPSP a protocol that is defined between sender and receiver and is initiated when the sender calls an SPSP endpoint of the receiver's.

This allows us to support many receiver identifier formats (acct: URIs, mobile numbers, PANs, national IDs etc) and all that is required is a way to resolve an SPSP service endpoint from that identifier. 

This has the advantage of being customizable based on context so it can use a global registry (like DNS and WebFinger) a private registry (maybe all identifiers of a certain type are resolved from a single registry that requires the sender to be authorized) or even just some rules that convert the identifier into a URL.

But, if you do that then basically you're just left with ITP. So may be the answer is to split the definition of ITP up into: a) flow and data model and then b) a separate definition of the actual data formats and how the flow is implemented in something like HTTP.

So I would take "discovery" out of SPSP and say that SPSP defines an extensible HTTP protocol for querying a URL endpoint (as the sender) with either:
 1. An identifier for the receiver and the amount and currency they wish the receiver to get
 2. An invoice identifier

The response from the endpoint should be:
 1. The data required to build the ILP header (Including the ILP address, condition, timeout and destination amount).
 2. Any other data requested by the sender

I think we should have distinct setup protocols for use cases where the amount to be received is fixed (SPSP) and where the amount that will be sent is fixed.

This allows us to fully decouple quoting from setup which I think would also simplify things a lot

**Comment by emschwartz** [comment]
> I'd like to decouple the WebFinger portion 

Note the line from the spec: "Whenever possible, URIs should be exchanged out-of-band and discovery should be skipped. However, in some cases, it may be useful to have a standardized user-friendly identifier. This discovery method describes how to resolve such an identifier to a queryable SPSP endpoint."

You could have something else resolve to that endpoint but I think it would still be useful to have a standard way of doing it (which makes it simple ;) ) -- otherwise you _need_ yet another layer to make this work.

> I think we should have distinct setup protocols for use cases where the amount to be received is fixed (SPSP) and where the amount that will be sent is fixed.

As far as I understand it, SPSP is supposed to handle fixed source amounts as well

**Comment by adrianhopebailie** [comment]
> As far as I understand it, SPSP is supposed to handle fixed source amounts as well

Yes, which I think makes it more complicated for the sake of one use case.

Notice how in almost all use cases there is simply a "setup" step where the sender tells the receiver they wish to pay them and in response they get all the data they need to do that.

But, if there is a fixed send amount then the whole flow changes to a "query" first to get the details of the receiver required for quoting, the ILP address (and currency?). Then does some quoting and then does the "setup" (except that this time they know the ILP address already).

So it's only the latter that is really different to ITP right?

But, SPSP has a whole lot of extra steps which I wonder about. The first HTTP request/response seems unnecessary.

If we can assume we know either:
1.  The receiving amount and some identifier for the receiver OR
2. Some invoice identifier

We can go straight to setup with something like:

``` http
POST /api/spsp/ HTTP/1.1
Host: red.ilpdemo.org
Accept: application/json

{
  "destination_account_identifier": "bob@ilpdemo.org",
  "destination_amount": "10.40",
  "verification_data" : [ "full_name", "email"]
}
```
``` http
HTTP/1.1 201 Created
Content-Type: application/json
{
  "ilp_header" : {
    "address": "ilpdemo.red.bob",
    "amount": "10.40",
    "timeout": "2016-08-04 09:00:00.000 UTC",
    "condition": "cc:1:1:47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU:1"
  },
  "verification_data" : {
    "full_name" : "Bob the Builder",
    "email" : null,
  }
}
```

OR

``` http
POST /api/spsp/ HTTP/1.1
Host: red.ilpdemo.org
Accept: application/json

{
  "destination_invoice": "ilpdemo.org-INV-0001",
  "verification_data" : [ "full_name", "email"]
}
```
``` http
HTTP/1.1 201 Created
Content-Type: application/json
{
  "ilp_header" : {
    "address": "ilpdemo.red.bob",
    "amount": "10.40",
    "timeout": "2016-08-04 09:00:00.000 UTC",
    "condition": "cc:1:1:47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU:1"
  },
  "memo" : "ilpdemo.org-INV-0001",
  "verification_data" : {
    "full_name" : "Bob the Builder",
    "email" : null,
  }
}
```

**Comment by emschwartz** [comment]
> But, if there is a fixed send amount then the whole flow changes...

Yes, that does mean there is a different flow. But the argument for having it is that it's a common use case that the protocol designed to make common use cases seem simple should support. Arguably, it doesn't matter that much how complicated the actual SPSP protocol is as long as it makes _setting up payments_ simple for the user.

> So it's only the latter that is really different to ITP right?

ITP can be used either way. For a fixed source amount you just need to figure out how much the recipient should receive, then it's basically the same as if you had started with a fixed destination amount.

> But, SPSP has a whole lot of extra steps which I wonder about. The first HTTP request/response seems unnecessary.

That was what I originally thought but @justmoon's [point](https://github.com/interledger/rfcs/issues/65#issuecomment-237277661) was that although the query step may be optional, it is a requirement to have it so that a wallet UI can display things like the currency code or information about the invoice. It is not technically required if you just want to set up the payment, but the scope of this protocol is larger than that (one could argue that it needs a name change then...).

**Comment by adrianhopebailie** [comment]
> It is not technically required if you just want to set up the payment, but the scope of this protocol is larger than that (one could argue that it needs a name change then...).

In that case it shouldn't be a required. The API should be designed so that those two steps are not tightly coupled and you could go straight to getting the payment request if you want to.

I think we're trying to stick to REST style here too strictly and have different endpoint URLs for different things and it's compromising the protocol a bit.

Maybe the answer is to have a base URL that we consider the entry-point for all functions and then have standard endpoint URLs off that base. This allows the sender to discover the base URL through some mechanism like WebFinger and then call the other endpoints as required.

**Comment by emschwartz** [comment]
As far as I understand it now, the Query functionality is a product requirement, even if it is not "necessary" to set up a payment. If it isn't a requirement to call that endpoint I don't see what the problem is.

Maybe one way to think of SPSP is a single API and a set of "protocols" (in the "series of steps" sense of the word) that makes a number of common use cases simple.

> Maybe the answer is to have a base URL that we consider the entry-point for all functions

Why would that make a difference? I thought about that but if there are distinct functions an SPSP server is supposed to handle let's make as few assumptions as possible about where the necessary endpoints are.

**Comment by adrianhopebailie** [comment]
> If it isn't a requirement to call that endpoint I don't see what the problem is.

To get the URL of the setup endpoint you have to call the query endpoint.

Why not simply have a base like `http://red.ilpdemo/com/api/spsp` and then relative endpoints like `./payment_requests/`, `./accounts/` etc

If I have everything I need to get a payment request I just POST to `http://red.ilpdemo/com/api/spsp/payment_requests/`

If I need to get account details because I need to determine the ILP address or currency I can GET
`http://red.ilpdemo/com/api/spsp/accounts/?identifer=bob@red.ilpdemo.org`

I'd likely have different security policies on these but I'd still be able to map all identifiers to one URL if I want to as a ledger or I could have a different base per identifier or account.

**Comment by emschwartz** [comment]
@justmoon ^?

**Comment by adrianhopebailie** [comment]
In thinking about the discovery phase (identifer -> service endpoint) I think it would be helpful to decouple this from the setup.

If we simply say that any identifier for a receiver must be resolvable to a URL and that URL is expected to be the base for the setup services then we have all we need.

The specific services that the sender calls will be dependent on the use case and what data they already have to setup the payment.

Also, the different service endpoints could redirect to services hosted somewhere else entirely? 

Alternatively we can adopt something like (HATEOS)[https://en.wikipedia.org/wiki/HATEOAS], (Hydra)[http://www.markus-lanthaler.com/hydra/]. 

The URI scheme of the identifier helps decide which discovery protocol to use (example: acct: means use WebFinger). Clients can infer the URI scheme from the format of the identifier too.

**Comment by emschwartz** [comment]
I don't have a very strong opinion about whether Discovery should be included, but I don't see much of a problem with including a recommended Discovery method (e.g. Webfinger) as an optional step.

The bigger question is how we should interact with the SPSP endpoint. It seems like we have the following options:

## REST/HATEOAS

You (have to) query the receiver endpoint to get the other links. The advantage of doing this in general is that since it is dynamic it can accommodate functionality moving to different locations in the medium to long term. The downside is that it adds an extra round trip.

Note it might be worth using JSON-LD/schema.org schemas if we a number of optional fields like person images and other identifying info.

## Base endpoint + known extensions

This is the opposite of the first option. The advantage would be that you would avoid the extra round trip of communication. The downside would be that it would be fairly inflexible to changes later, and it's not very "Web-y".

This is somewhat similar to the way Webfinger works. This style seems to have gone out of fashion (if it ever was in fashion) in the Web community though. Note there is a spec for [Defining Well-Known URIs](https://tools.ietf.org/html/rfc5785).

## (JSON-)RPC

The SPSP receiver endpoint would be the only one you need to interact with. You send it different messages and it responds accordingly. Again not very Web-y but maybe a little less icky (that's a technical term ;) ) than URL concatenation.

Any others? I honestly don't love any of these options but I would have a slight preference for the first option. If this is a protocol meant for when a user is actually looking at a UI the extra round trip should be fine.

**Comment by adrianhopebailie** [comment]
> I honestly don't love any of these options but I would have a slight preference for the first option. If this is a protocol meant for when a user is actually looking at a UI the extra round trip should be fine.

👍

**Comment by justmoon** [comment]
> Any others?

You could use the same URL, but GET for querying and POST for setup. This is a very common, age-old pattern for forms - you GET the page with the form, fill it in and POST it back to the same URL.

That would be very easy to develop against, very clean (only one URL, no concatenation, no mixing REST and RPC) and web-y (URLs are resources, found via links, verbs to distinguish interactions.)

**Comment by emschwartz** [comment]
👍 👍 I like that a lot better than the other options.

**Comment by emschwartz** [comment]
On a different note, @justmoon mentioned in an [earlier comment](https://github.com/interledger/rfcs/issues/65#issuecomment-237277661) the following as a use case for SPSP:
> Recurring/subscriptions
>
>    As a customer, I want to be able to see the status of subscriptions, the next payment due and be able to cancel them.

I don't think this should be part of SPSP. Normally subscriptions are done with pull payments, which means we would want to think about it when we design a pull-based scheme on top of ILP. This is not simple, so it should be left for another spec.

If you are doing subscriptions with push based payments, the controls for this would be on the sender's payment system, not the receiver's side, so that doesn't need to be in a standard protocol.

**Comment by adrianhopebailie** [comment]
> You could use the same URL, but GET for querying and POST for setup. This is a very common, age-old pattern for forms - you GET the page with the form, fill it in and POST it back to the same URL.

Would this not be too limiting though?

There are quite a number of functions that one may want to offer at this endpoint and the service used will be dependent on the context. A sender may only need to get the ILP address or they may wish to perform the full SPSP flow or maybe something entirely new like get a photograph of the sender.

HATEOS is effectively this but you first follow-your-nose hypermedia-style to get the right URL for the service you need. Then it's GET for data and POST for setup/execute.

An interesting _option_ might be the OPTIONS verb which when executed against the endpoint URL could return the details of what services are available where?

**Comment by justmoon** [comment]
> Would this not be too limiting though? There are quite a number of functions that one may want to offer at this endpoint and the service used will be dependent on the context.

I had the same thought, but this is the **Simple** Payment Setup Protocol. I think the final set of functionality will be some function of:

1. Get a static object describing this receiver
2. Submit a static object describing the payment(s) I'm intending to do

Anything more complicated than that should be beyond the scope of SPSP.

**Comment by adrianhopebailie** [comment]
A note to this, that we then need a way to provide some query parameters in the GET that allow the sender to specify what data they need.

The response format should allow the receiver endpoint to provide another URL to the sender (maybe in the form of a rel link) that directs them to another service for getting that data.

This is a requirement in the following use case (as an example):

Sender system is a digital wallet and the sending user enters the mobile number of the receiver as the identifier. The wallet uses some predefined discovery mechanism to resolve a URL from that identifier and this is assumed to be the SPSP receiver endpoint for the receiver identified by that URL.

The wallet needs to get:
- ILP address of the receiver
- Currency of the receiving account
- Full name of the receiver for display purposes
- Currency code of the receiving account for display purposes
- Photograph of the receiver for validation

The SPSP receiver by default can return the first two but not the other three, it delegates that to other services. For SPSP to be extensible in this way it needs a way to provides the URLs for those services.

Admittedly full HATEOS and Hydra based systems are maybe too generic. They are attempting to solve for fully self-describing systems where we have the need to 1) be simple and 2) make use f the context we have (this is an SPSP receiver endpoint, the ontology of the requests and data should be well defined).

1. Should we use JSON-LD and define a context for SPSP requests and responses that can pull in other well-known ontologies?
2. Should we define a few well-known service endpoints like (accounts, users etc) and recognize when these are requested?
3. Any other ideas?

**Comment by emschwartz** [comment]
My understanding of the scope of SPSP right now is that we would want it to include these (though I'm not entirely sure how):

> - Full name of the receiver for display purposes
> - Currency code of the receiving account for display purposes
> - Photograph of the receiver for validation

Re:
> Should we use JSON-LD and define a context for SPSP requests and responses that can pull in other well-known ontologies?

I was thinking of suggesting that today. My main hesitation is that it might not help very much. If you get back a JSON-LD response with properties you don't understand, how much can the fact that it's JSON-LD help you? We could try to conform to the schema.org schemas if that would help make extensions people could add be more standardized and predictable.

> Should we define a few well-known service endpoints like (accounts, users etc) and recognize when these are requested?

I think this should be out of scope for SPSP.

**Comment by adrianhopebailie** [comment]
> We could try to conform to the schema.org schemas if that would help make extensions people could add be more standardized and predictable.

That would probably be the most sensible and solves the:

> My understanding of the scope of SPSP right now is that we would want it to include these (though I'm not entirely sure how)

```http
GET /api/spsp/7ee0bb55-f645-4d83-b4df-f878b9bf1b7b HTTP/1.1
Host: red.ilpdemo.org
Accept: application/json+ld

HTTP/1.1 200 Success
Content-Type: application/json+ld
{
  "@context": "http://interledger.org/json-ld/spsp",
  "@type": "Payee",
  "@id": "http://red.ilpdemo.org/api/spsp/7ee0bb55-f645-4d83-b4df-f878b9bf1b7b",
  "name": "Bob the Builder",
  "ilpAddress": "ilpdemo.red.bob",
  "account": 
  {
      "currency": "USD",
  },
  "telephone": "(425) 123-4567"
}
```
We should define an SPSP receiver context with types that inherits from some schema.org types. (The example above inherits the "name" property from the schema.org Person type)

We could also allow the GET to take a SPARQL query encoded in the query string to specify which properties you want in the response but that might be too much overhead right now.

Perhaps something like the following:

```http
GET /api/spsp/7ee0bb55-f645-4d83-b4df-f878b9bf1b7b?q=[name,ilpAddress,account.currency,telephone] HTTP/1.1
Host: red.ilpdemo.org
Accept: application/json+ld
```

Although I am not sure we want to be re-inventing this since SPARQL, OData etc do already deal with this.
