### ISSUE TITLE
RFC-2: Clarify that the binary encoding for conditions uses a variable-length encoding for fingerprints and why

### ISSUE THREAD

**Issue by justmoon** [interledger/rfcs#69]
The fingerprint in binary-encoded conditions is encoded as a standard variable-length octet string.

The reason is that different condition types may use different hashing functions and therefore have different length hashes. (You could tell from the type what the length should be, but we felt it was useful to be able to find the end of a condition in a binary stream even if you didn't recognize the type.)

This should be mentioned explicitly in the spec.

**Comment by r-marques** [comment]
It may be useful to take a look at the multihash spec from ipfs https://github.com/multiformats/multihash

The output of a multihash encodes together the hash function used, the size of the digest, and the output of the hash function

**Comment by justmoon** [comment]
@r-marques Yeah, definitely a good sign that we both independently decided on the same format. (Crypto conditions add the max fulfillment length and use a two-byte instead of a one-byte type. But that's just because we have a slightly broader scope than multihash.)

**Comment by justmoon** [comment]
This issue basically says that draft-01 (non-breaking changes) of the I-D should explain why we currently use variable-length fingerprints, even thought draft-02 (breaking changes) *may* make them fixed length (depending on what we decide in #106)
