### ISSUE TITLE
RFC-2: OER encoding of featureBitmask

### ISSUE THREAD

**Issue by nbougalis** [interledger/rfcs#71]
Currently the RFC specifies the binary representation of a cryptocondition as follows:

    Condition ::= SEQUENCE {
        type ConditionType,
        featureBitmask OCTET STRING,
        fingerprint OCTET STRING,
        maxFulfillmentLength INTEGER (0..MAX)
    }

Notice that `featureBitmask`, which is an integer, is defined as an `OCTET STRING`. According to the OER spec (2.6, clause 2) variable-length octet strings are encoded as:

> otherwise, the encoding of the octet string value consists of a length prefix as described in 2.11, followed by the octets of the string.

Notice that the endianess of an octet string is unspecified; with `featureBitmask` being an integer an implementation running on a little-endian architecture might, reasonably, encode the `featureBitmask` differently than one running on big-endian.

I suggest that we instead encode the field as an INTEGER of unknown length, under section 2.2, which explicitly specifies endianess ("All integer encodings are in big endian order."). So the `featureBitmask` would fall under clause 10:

> otherwise, the integer value is encoded as a length prefix as described in 2.11, followed by a ***signed*** binary integer occupying a variable number of octets; the length prefix contains the number of subsequent octets.

The emphasis on "signed" is mine: since the integer is represented as signed, if the high bit of the first encoded byte would be set, the encoder should add a leading `0` byte in the representation since the value is unsigned.

This is a change to the binary representation of cryptoconditions and the library itself will need to be updated.

All references to sections are based on this document: http://www.oss.com/asn1/resources/books-whitepapers-pubs/Overview%20of%20OER.pdf

**Comment by adrianhopebailie** [comment]
Would it not be simply to just specify the endianess?

Network byte order is likely assumed by most when unspecified and is probably the right one to specify.

**Comment by nbougalis** [comment]
What's the byte order of an octet string? Octets, themselves, have no endianess.

**Comment by justmoon** [comment]
Totally agree with the issue about endianness. @adrianhopebailie is right that we could just say in our spec what it is, but I think @nbougalis' solution to use `INTEGER` is elegant.

Just one addition: I think it should be an unsigned integer (`INTEGER (0..MAX)`, see 2.2, clause 5), that way you avoid the extra complexity of the sign bit and the implementation would not have to change.

**Comment by nbougalis** [comment]
I'm fine with either @adrianhopebailie's suggestion or the bounded `INTEGER`.

**Comment by justmoon** [comment]
Why not do both - let's use the `INTEGER (0..MAX)` and still explicitly mention the endianness. If I am used to OER I do the right thing, if I RTFM I do the right thing. Everyone is happy. :)
