### ISSUE TITLE
RFC-2: Encoding of preimage fulfillment payload

### ISSUE THREAD

**Issue by adrianhopebailie** [interledger/rfcs#85]
The spec says:

> The fulfillment payload of a PREIMAGE-SHA-256 condition is the preimage.

What is the specific OER encoding? i.e. Is this a variable length OCTET STRING (i.e with a length prefix) 

I assume yes?

**Comment by justmoon** [comment]
No, it is just the literal preimage. (The payload already always has a length prefix - not much point adding a second one.)

**Comment by adrianhopebailie** [comment]
Aaah, okay. I misinterpreted the spec as each different condition type payload being a different sequence of fields as opposed to sub-fields of the payload field.
