### ISSUE TITLE
RFC-2: Replace weighted threshold conditions with regular (unweighted) thresholds

### ISSUE THREAD

**Issue by justmoon** [interledger/rfcs#87]
Having support for weighted thresholds is adding significant complexity. Most signficantly, it requires implementations to solve a version of the 0-1 knapsack problem everytime they calculate the `maxFulfillmentLength` of a threshold condition. To make matters worse, the algorithm has a complexity of _O(nW)_ where `n` is the number of items and `W` is the threshold. Most practical values may be fine, but it's still a possible DoS vector.

The use cases for weighted thresholds are pretty thin and most of them can likely be served by transforming the weighted threshold circuit into an unweighted one. Also #86 might be good enough for small weights, since we could just refer to the same condition multiple times.

**Comment by adrianhopebailie** [comment]
Is the proposal to add a new type called `WEIGHTED-THRESHOLD-SHA-256` which is the same as the current `THRESHOLD-SHA-256` and then drop the weights from the current definition?

It's likely that few people will implement `WEIGHTED-THRESHOLD-SHA-256` if they are overly complex and unlikely to be used but that might just be for the ILP use case?

**Comment by justmoon** [comment]
Yes, although I'd recommend that we do not define `WEIGHTED-THRESHOLD-SHA-256` at this stage, but rather wait for a need to arise. I.e. somebody to show up who has a use case for it. If that never happens, so be it.

**Comment by justmoon** [comment]
Implemented in draft-02.
