### ISSUE TITLE
RFC-9: Fixed source amount

### ISSUE THREAD

**Issue by vhpoet** [interledger/rfcs#89]
The doc [tells me](https://github.com/interledger/rfcs/blob/master/0009-simple-payment-setup-protocol/0009-simple-payment-setup-protocol.md#fixed-source-amount) to request a quote (step4) before doing a request (step7), but the Ilp module [needs a `request`](https://github.com/interledger/js-ilp/blob/e3af32f30d92a739024ab1e27308a3601dec5dc8/src/lib/sender.js#L30) to do a `quote`. Am I misunderstanding something?

**Comment by emschwartz** [comment]
Right now `js-ilp` only supports the functionality needed to create payment requests and pay for them. We can add a plain quote function to `js-ilp`. See https://github.com/interledger/js-ilp/issues/26
