### ISSUE TITLE
RFC-4: PROPOSAL: Add Error Types

### ISSUE THREAD

**Issue by bensharaf** [interledger/rfcs#93]
# Reasoning

Currently, most functions in the LPI return promises which will be rejected if something goes wrong. The interface assumes that all errors emitted have plugin-specific types and messages. This poses a problem when it's important to distinguish different failure types (eg. https://github.com/interledger/rfcs/pull/84)

Adding some standard error types would make the error values of functions unambiguous. For instance, a malformed transfer will appear different from a repeat transfer. In the case of plugin-specific errors, the generic `Error` could still be used.

[Ilp-plugin-tests](https://github.com/interledger/js-ilp-plugin-tests) currently only sees whether functions failed or succeeded. A function that is supposed to fail could be failing for the wrong reason, which would not be picked up by the tests. These mistakes lead to bugs, but are not possible to prevent while keeping the tests cross-plugin. Error types would eliminate this problem.

This change would also let tools such as [ilp-connector](https://github.com/interledger/js-ilp-connector) give more descriptive errors.

# Possible Error Types

| Function | Error Types Returned |
|----------|------------|
| `connect()` | `InvalidFieldsError`, `UnreachableError` |
| `getFulfillment()` | `TransferNotFoundError`, `MissingFulfillmentError` |
| `send()` | `InvalidFieldsError`, `NotAcceptedError`, `RepeatError` |
| `fulfillCondition()` | `InvalidFieldsError`, `TransferNotFoundError`, `NotAcceptedError`, `RepeatError` |
| `replyToTransfer` | `TransferNotFoundError` |
| `rejectIncomingTransfer` | `TransferNotFoundError`, `NotAcceptedError`, `RepeatError` |

- `InvalidFieldsError` - The arguments or configuration were invalidated client-side.
- `UnreachableError` - Could not connect due to network issues.
- `TransferNotFoundError` - A Transfer with the given ID doesn't exist.
- `MissingFulfillmentError` - Transfer has not yet been fulfilled.
- `RepeatError` - That transfer has already been sent/fulfilled/rejected.
- `NotAcceptedError` - The ledger rejected the operation (eg. If balance is too low, or fulfillment doesn't match condition).

**cc** @justmoon @emschwartz @adrianhopebailie

**Comment by emschwartz** [comment]
👍 . Another class of errors has to do with transfers being expired (for `getFulfillment`, `send`, `fulfillCondition`).

With all of these it's important to know whether the correct behavior is to retry the action or if it will always fail. For example with the `MissingFulfillment` error, that really means there is no fulfillment _yet_ and you should retry later because the transfer state isn't finalized.

**Comment by adrianhopebailie** [comment]
👍 

Are we differentiating between errors and exceptions?
Errors are expected and planned for whereas exceptions usually are not.
